/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rockit_model_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[12] = {6, 6, 0, 1, 1, 3, 3, 3, 3, 5, 0, 1};
static const casadi_int casadi_s1[12] = {6, 6, 0, 1, 2, 2, 2, 2, 3, 2, 2, 0};
static const casadi_int casadi_s2[15] = {6, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[12] = {6, 4, 0, 2, 3, 4, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s4[14] = {4, 6, 0, 1, 2, 3, 4, 5, 5, 0, 0, 1, 2, 3};
static const casadi_int casadi_s5[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s6[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s7[3] = {0, 0, 0};
static const casadi_int casadi_s8[3] = {6, 0, 0};

/* rockit_model_impl_dae_jac_x_xdot_u_z:(i0[6],i1[6],i2[4],i3[],i4[])->(o0[6x6,3nz],o1[6x6,6nz],o2[6x4,5nz],o3[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, w2, w3, *w4=w+6, w5, w6, w7, *w11=w+15, *w12=w+18, *w13=w+21, *w14=w+27, *w15=w+32, *w16=w+36, *w17=w+41;
  /* #0: @0 = zeros(6x6,3nz) */
  casadi_clear(w0, 3);
  /* #1: @1 = input[2][0] */
  w1 = arg[2] ? arg[2][0] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = sin(@2) */
  w3 = sin( w2 );
  /* #4: @4 = ones(6x1) */
  casadi_fill(w4, 6, 1.);
  /* #5: {@5, NULL, @6, NULL, NULL, NULL} = vertsplit(@4) */
  w5 = w4[0];
  w6 = w4[2];
  /* #6: @3 = (@3*@6) */
  w3 *= w6;
  /* #7: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #8: @3 = (-@3) */
  w3 = (- w3 );
  /* #9: @7 = cos(@2) */
  w7 = cos( w2 );
  /* #10: @7 = (@7*@6) */
  w7 *= w6;
  /* #11: @1 = (@1*@7) */
  w1 *= w7;
  /* #12: @8 = 00 */
  /* #13: @9 = 00 */
  /* #14: @10 = 00 */
  /* #15: @7 = input[0][0] */
  w7 = arg[0] ? arg[0][0] : 0;
  /* #16: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #17: @7 = (@7*@5) */
  w7 *= w5;
  /* #18: @11 = vertcat(@3, @1, @8, @9, @10, @7) */
  rr=w11;
  *rr++ = w3;
  *rr++ = w1;
  *rr++ = w7;
  /* #19: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<3; ++i) *rr++ = (- *cs++ );
  /* #20: @12 = @11[:3] */
  for (rr=w12, ss=w11+0; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #21: (@0[:3] = @12) */
  for (rr=w0+0, ss=w12; rr!=w0+3; rr+=1) *rr = *ss++;
  /* #22: @12 = @0' */
  casadi_trans(w0,casadi_s1, w12, casadi_s0, iw);
  /* #23: output[0][0] = @12 */
  casadi_copy(w12, 3, res[0]);
  /* #24: @4 = zeros(6x6,6nz) */
  casadi_clear(w4, 6);
  /* #25: @13 = ones(6x1) */
  casadi_fill(w13, 6, 1.);
  /* #26: (@4[:6] = @13) */
  for (rr=w4+0, ss=w13; rr!=w4+6; rr+=1) *rr = *ss++;
  /* #27: @13 = @4' */
  casadi_trans(w4,casadi_s2, w13, casadi_s2, iw);
  /* #28: output[1][0] = @13 */
  casadi_copy(w13, 6, res[1]);
  /* #29: @14 = zeros(4x6,5nz) */
  casadi_clear(w14, 5);
  /* #30: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #31: @15 = ones(4x1) */
  casadi_fill(w15, 4, 1.);
  /* #32: {@1, @7, @5, @6} = vertsplit(@15) */
  w1 = w15[0];
  w7 = w15[1];
  w5 = w15[2];
  w6 = w15[3];
  /* #33: @3 = (@3*@1) */
  w3 *= w1;
  /* #34: @2 = sin(@2) */
  w2 = sin( w2 );
  /* #35: @2 = (@2*@1) */
  w2 *= w1;
  /* #36: @8 = 00 */
  /* #37: @16 = vertcat(@3, @2, @7, @5, @6, @8) */
  rr=w16;
  *rr++ = w3;
  *rr++ = w2;
  *rr++ = w7;
  *rr++ = w5;
  *rr++ = w6;
  /* #38: @16 = (-@16) */
  for (i=0, rr=w16, cs=w16; i<5; ++i) *rr++ = (- *cs++ );
  /* #39: @17 = @16[:5] */
  for (rr=w17, ss=w16+0; ss!=w16+5; ss+=1) *rr++ = *ss;
  /* #40: (@14[:5] = @17) */
  for (rr=w14+0, ss=w17; rr!=w14+5; rr+=1) *rr = *ss++;
  /* #41: @17 = @14' */
  casadi_trans(w14,casadi_s4, w17, casadi_s3, iw);
  /* #42: output[2][0] = @17 */
  casadi_copy(w17, 5, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rockit_model_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rockit_model_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rockit_model_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void rockit_model_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_impl_dae_jac_x_xdot_u_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real rockit_model_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rockit_model_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 7;
  if (sz_w) *sz_w = 46;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
