/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rockit_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_flip CASADI_PREFIX(flip)
#define casadi_interpn CASADI_PREFIX(interpn)
#define casadi_interpn_interpolate CASADI_PREFIX(interpn_interpolate)
#define casadi_interpn_weights CASADI_PREFIX(interpn_weights)
#define casadi_low CASADI_PREFIX(low)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_interpn_weights(casadi_int ndim, const casadi_real* grid, const casadi_int* offset, const casadi_real* x, casadi_real* alpha, casadi_int* index, const casadi_int* lookup_mode) {
  casadi_int i;
  for (i=0; i<ndim; ++i) {
    casadi_int ng, j;
    casadi_real xi;
    const casadi_real* g;
    xi = x ? x[i] : 0;
    g = grid + offset[i];
    ng = offset[i+1]-offset[i];
    j = index[i] = casadi_low(xi, g, ng, lookup_mode[i]);
    alpha[i] = (xi-g[j])/(g[j+1]-g[j]);
  }
}

void casadi_interpn_interpolate(casadi_real* res, casadi_int ndim, const casadi_int* offset, const casadi_real* values, const casadi_real* alpha, const casadi_int* index, const casadi_int* corner, casadi_real* coeff, casadi_int m) {
  casadi_real c;
  casadi_int ld, i;
  c=1;
  ld=1;
  for (i=0; i<ndim; ++i) {
    if (coeff) *coeff++ = c;
    if (corner[i]) {
      c *= alpha[i];
    } else {
      c *= 1-alpha[i];
    }
    values += (index[i]+corner[i])*ld*m;
    ld *= offset[i+1]-offset[i];
  }
  if (coeff) {
    for (i=0;i<m;++i) res[i] += values[i];
  } else {
    for (i=0;i<m;++i) res[i] += c*values[i];
  }
}

casadi_int casadi_flip(casadi_int* corner, casadi_int ndim) {
  casadi_int i;
  for (i=0; i<ndim; ++i) {
    if (corner[i]) {
      corner[i]=0;
    } else {
      corner[i]=1;
      return 1;
    }
  }
  return 0;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_interpn(casadi_real* res, casadi_int ndim, const casadi_real* grid, const casadi_int* offset, const casadi_real* values, const casadi_real* x, const casadi_int* lookup_mode, casadi_int m, casadi_int* iw, casadi_real* w) {
  casadi_real* alpha;
  casadi_int *index, *corner;
  alpha = w; w += ndim;
  index = iw; iw += ndim;
  corner = iw; iw += ndim;
  casadi_interpn_weights(ndim, grid, offset, x, alpha, index, lookup_mode);
  casadi_clear_casadi_int(corner, ndim);
  casadi_clear(res, m);
  do {
    casadi_real* coeff = 0;
    casadi_interpn_interpolate(res, ndim, offset, values,
      alpha, index, corner, coeff, m);
  } while (casadi_flip(corner, ndim));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

#ifndef casadi_nan
  #define casadi_nan NAN
#endif

static const casadi_int casadi_s0[1] = {0};
static const casadi_int casadi_s1[2] = {0, 6};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {3};
static const casadi_int casadi_s4[2] = {0, 22};
static const casadi_int casadi_s5[6] = {0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s6[37] = {1, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s7[54] = {18, 17, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17};
static const casadi_int casadi_s8[39] = {1, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s9[1] = {2};
static const casadi_int casadi_s10[2] = {0, 20};
static const casadi_int casadi_s11[12] = {6, 4, 0, 2, 3, 4, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s12[14] = {4, 6, 0, 1, 2, 3, 4, 5, 5, 0, 0, 1, 2, 3};
static const casadi_int casadi_s13[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s14[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s15[31] = {6, 4, 0, 6, 12, 18, 24, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s16[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s17[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};

static const casadi_real casadi_c0[6] = {0., 2.0000000000000001e-01, 4.0000000000000002e-01, 6.0000000000000009e-01, 8.0000000000000004e-01, 1.};
static const casadi_real casadi_c1[18] = {0., 3.2666666666666656e-02, 6.6666666666666666e-02, 1.3333333333333333e-01, 2.0000000000000004e-01, 2.6666666666666666e-01, 3.3333333333333331e-01, 4.0000000000000008e-01, 4.6666666666666673e-01, 5.3333333333333333e-01, 6.0000000000000009e-01, 6.6666666666666663e-01, 7.3333333333333339e-01, 8.0000000000000016e-01, 8.6666666666666670e-01, 9.3333333333333324e-01, 9.6733333333333338e-01, 1.};
static const casadi_real casadi_c2[22] = {0., 0., 0., 0., 9.7999999999999976e-02, 1.0200000000000004e-01, 2.0000000000000001e-01, 2.9799999999999999e-01, 3.0200000000000005e-01, 4.0000000000000002e-01, 4.9800000000000000e-01, 5.0200000000000011e-01, 6.0000000000000009e-01, 6.9800000000000006e-01, 7.0200000000000007e-01, 8.0000000000000004e-01, 8.9800000000000002e-01, 9.0200000000000002e-01, 1., 1., 1., 1.};
static const casadi_real casadi_c3[34] = {-3.0612244897959194e+01, 3.0612244897959194e+01, -2.9411764705882344e+01, 2.9411764705882344e+01, -15., 15., -15., 15., -15., 15., -15., 15., -15., 15., -1.4999999999999995e+01, 1.4999999999999995e+01, -1.4999999999999995e+01, 1.4999999999999995e+01, -1.4999999999999995e+01, 1.4999999999999995e+01, -1.5000000000000004e+01, 1.5000000000000004e+01, -1.5000000000000004e+01, 1.5000000000000004e+01, -1.5000000000000004e+01, 1.5000000000000004e+01, -1.5000000000000004e+01, 1.5000000000000004e+01, -1.5000000000000004e+01, 1.5000000000000004e+01, -2.9411764705882362e+01, 2.9411764705882362e+01, -3.0612244897959194e+01, 3.0612244897959194e+01};
static const casadi_real casadi_c4[20] = {0., 0., 0., 9.7999999999999976e-02, 1.0200000000000004e-01, 2.0000000000000001e-01, 2.9799999999999999e-01, 3.0200000000000005e-01, 4.0000000000000002e-01, 4.9800000000000000e-01, 5.0200000000000011e-01, 6.0000000000000009e-01, 6.9800000000000006e-01, 7.0200000000000007e-01, 8.0000000000000004e-01, 8.9800000000000002e-01, 9.0200000000000002e-01, 1., 1., 1.};
static const casadi_real casadi_c5[4] = {casadi_nan, casadi_nan, casadi_nan, casadi_nan};

/* linear:(x,c[6])->(f) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    if (res[0]) {
        casadi_interpn(res[0], 1, casadi_c0, casadi_s1, arg[1], arg[0], casadi_s0, 1, iw, w);
      }
  return 0;
}

/* x:(x,c[6])->(f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+2;
  casadi_real w0, *w1=w+10, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+46, w21;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w1);
  /* #2: {@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19} = horzsplit(@1) */
  w2 = w1[0];
  w3 = w1[1];
  w4 = w1[2];
  w5 = w1[3];
  w6 = w1[4];
  w7 = w1[5];
  w8 = w1[6];
  w9 = w1[7];
  w10 = w1[8];
  w11 = w1[9];
  w12 = w1[10];
  w13 = w1[11];
  w14 = w1[12];
  w15 = w1[13];
  w16 = w1[14];
  w17 = w1[15];
  w18 = w1[16];
  w19 = w1[17];
  /* #3: @20 = input[1][0] */
  casadi_copy(arg[1], 6, w20);
  /* #4: @21 = linear(@2, @20) */
  arg1[0]=(&w2);
  arg1[1]=w20;
  res1[0]=(&w21);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #5: @2 = linear(@3, @20) */
  arg1[0]=(&w3);
  arg1[1]=w20;
  res1[0]=(&w2);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @20) */
  arg1[0]=(&w4);
  arg1[1]=w20;
  res1[0]=(&w3);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @20) */
  arg1[0]=(&w5);
  arg1[1]=w20;
  res1[0]=(&w4);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @20) */
  arg1[0]=(&w6);
  arg1[1]=w20;
  res1[0]=(&w5);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @20) */
  arg1[0]=(&w7);
  arg1[1]=w20;
  res1[0]=(&w6);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @20) */
  arg1[0]=(&w8);
  arg1[1]=w20;
  res1[0]=(&w7);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @20) */
  arg1[0]=(&w9);
  arg1[1]=w20;
  res1[0]=(&w8);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @20) */
  arg1[0]=(&w10);
  arg1[1]=w20;
  res1[0]=(&w9);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @20) */
  arg1[0]=(&w11);
  arg1[1]=w20;
  res1[0]=(&w10);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @20) */
  arg1[0]=(&w12);
  arg1[1]=w20;
  res1[0]=(&w11);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @20) */
  arg1[0]=(&w13);
  arg1[1]=w20;
  res1[0]=(&w12);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @20) */
  arg1[0]=(&w14);
  arg1[1]=w20;
  res1[0]=(&w13);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @20) */
  arg1[0]=(&w15);
  arg1[1]=w20;
  res1[0]=(&w14);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @20) */
  arg1[0]=(&w16);
  arg1[1]=w20;
  res1[0]=(&w15);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @20) */
  arg1[0]=(&w17);
  arg1[1]=w20;
  res1[0]=(&w16);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @20) */
  arg1[0]=(&w18);
  arg1[1]=w20;
  res1[0]=(&w17);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @20) */
  arg1[0]=(&w19);
  arg1[1]=w20;
  res1[0]=(&w18);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #22: @1 = horzcat(@21, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w1;
  *rr++ = w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #23: @21 = BSplineParametric(@0) */
  casadi_clear((&w21), 1);
  CASADI_PREFIX(nd_boor_eval)((&w21),1,casadi_c2,casadi_s4,casadi_s3,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #24: output[0][0] = @21 */
  if (res[0]) res[0][0] = w21;
  return 0;
}

/* linear:(x,c[6])->(f) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    if (res[0]) {
        casadi_interpn(res[0], 1, casadi_c0, casadi_s1, arg[1], arg[0], casadi_s0, 1, iw, w);
      }
  return 0;
}

/* y:(x,c[6])->(f) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+2;
  casadi_real w0, *w1=w+10, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+46, w21;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w1);
  /* #2: {@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19} = horzsplit(@1) */
  w2 = w1[0];
  w3 = w1[1];
  w4 = w1[2];
  w5 = w1[3];
  w6 = w1[4];
  w7 = w1[5];
  w8 = w1[6];
  w9 = w1[7];
  w10 = w1[8];
  w11 = w1[9];
  w12 = w1[10];
  w13 = w1[11];
  w14 = w1[12];
  w15 = w1[13];
  w16 = w1[14];
  w17 = w1[15];
  w18 = w1[16];
  w19 = w1[17];
  /* #3: @20 = input[1][0] */
  casadi_copy(arg[1], 6, w20);
  /* #4: @21 = linear(@2, @20) */
  arg1[0]=(&w2);
  arg1[1]=w20;
  res1[0]=(&w21);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #5: @2 = linear(@3, @20) */
  arg1[0]=(&w3);
  arg1[1]=w20;
  res1[0]=(&w2);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @20) */
  arg1[0]=(&w4);
  arg1[1]=w20;
  res1[0]=(&w3);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @20) */
  arg1[0]=(&w5);
  arg1[1]=w20;
  res1[0]=(&w4);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @20) */
  arg1[0]=(&w6);
  arg1[1]=w20;
  res1[0]=(&w5);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @20) */
  arg1[0]=(&w7);
  arg1[1]=w20;
  res1[0]=(&w6);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @20) */
  arg1[0]=(&w8);
  arg1[1]=w20;
  res1[0]=(&w7);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @20) */
  arg1[0]=(&w9);
  arg1[1]=w20;
  res1[0]=(&w8);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @20) */
  arg1[0]=(&w10);
  arg1[1]=w20;
  res1[0]=(&w9);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @20) */
  arg1[0]=(&w11);
  arg1[1]=w20;
  res1[0]=(&w10);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @20) */
  arg1[0]=(&w12);
  arg1[1]=w20;
  res1[0]=(&w11);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @20) */
  arg1[0]=(&w13);
  arg1[1]=w20;
  res1[0]=(&w12);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @20) */
  arg1[0]=(&w14);
  arg1[1]=w20;
  res1[0]=(&w13);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @20) */
  arg1[0]=(&w15);
  arg1[1]=w20;
  res1[0]=(&w14);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @20) */
  arg1[0]=(&w16);
  arg1[1]=w20;
  res1[0]=(&w15);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @20) */
  arg1[0]=(&w17);
  arg1[1]=w20;
  res1[0]=(&w16);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @20) */
  arg1[0]=(&w18);
  arg1[1]=w20;
  res1[0]=(&w17);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @20) */
  arg1[0]=(&w19);
  arg1[1]=w20;
  res1[0]=(&w18);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #22: @1 = horzcat(@21, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w1;
  *rr++ = w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #23: @21 = BSplineParametric(@0) */
  casadi_clear((&w21), 1);
  CASADI_PREFIX(nd_boor_eval)((&w21),1,casadi_c2,casadi_s4,casadi_s3,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #24: output[0][0] = @21 */
  if (res[0]) res[0][0] = w21;
  return 0;
}

/* ode:(x[6],u[4],z[0],p[16],t[1x1,0nz])->(ode[6],alg[0],quad[0]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+3, *rr, *ss;
  const casadi_int *cii;
  const casadi_real **arg1=arg+5;
  casadi_real w0, w1, w2, *w3=w+57, w4;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #4: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #5: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #6: @0 = (@0*@1) */
  w0 *= w1;
  /* #7: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #8: @0 = input[1][1] */
  w0 = arg[1] ? arg[1][1] : 0;
  /* #9: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #10: @0 = input[1][2] */
  w0 = arg[1] ? arg[1][2] : 0;
  /* #11: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  /* #12: @0 = input[1][3] */
  w0 = arg[1] ? arg[1][3] : 0;
  /* #13: output[0][4] = @0 */
  if (res[0]) res[0][4] = w0;
  /* #14: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #15: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #16: @2 = input[3][6] */
  w2 = arg[3] ? arg[3][10] : 0;
  /* #17: @3 = @2[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w3, ss=(&w2); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #18: @2 = x(@1, @3) */
  arg1[0]=(&w1);
  arg1[1]=w3;
  res1[0]=(&w2);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #19: @0 = (@0-@2) */
  w0 -= w2;
  /* #20: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #21: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #22: @4 = input[3][7] */
  w4 = arg[3] ? arg[3][11] : 0;
  /* #23: @3 = @4[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w3, ss=(&w4); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #24: @4 = y(@1, @3) */
  arg1[0]=(&w1);
  arg1[1]=w3;
  res1[0]=(&w4);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #25: @2 = (@2-@4) */
  w2 -= w4;
  /* #26: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #27: @0 = (@0+@2) */
  w0 += w2;
  /* #28: output[0][5] = @0 */
  if (res[0]) res[0][5] = w0;
  return 0;
}

/* jac_x:(x,c[6],out_f[1x1,0nz])->(jac[1x7]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_real **arg1=arg+3;
  casadi_real *w0=w+7, w1, *w2=w+15, *w3=w+32, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, *w22=w+68, w23, *w24=w+75;
  /* #0: @0 = zeros(7x1) */
  casadi_clear(w0, 7);
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = zeros(1x17) */
  casadi_clear(w2, 17);
  /* #3: @3 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w3);
  /* #4: {@4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21} = horzsplit(@3) */
  w4 = w3[0];
  w5 = w3[1];
  w6 = w3[2];
  w7 = w3[3];
  w8 = w3[4];
  w9 = w3[5];
  w10 = w3[6];
  w11 = w3[7];
  w12 = w3[8];
  w13 = w3[9];
  w14 = w3[10];
  w15 = w3[11];
  w16 = w3[12];
  w17 = w3[13];
  w18 = w3[14];
  w19 = w3[15];
  w20 = w3[16];
  w21 = w3[17];
  /* #5: @22 = input[1][0] */
  casadi_copy(arg[1], 6, w22);
  /* #6: @23 = linear(@4, @22) */
  arg1[0]=(&w4);
  arg1[1]=w22;
  res1[0]=(&w23);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @22) */
  arg1[0]=(&w5);
  arg1[1]=w22;
  res1[0]=(&w4);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @22) */
  arg1[0]=(&w6);
  arg1[1]=w22;
  res1[0]=(&w5);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @22) */
  arg1[0]=(&w7);
  arg1[1]=w22;
  res1[0]=(&w6);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @22) */
  arg1[0]=(&w8);
  arg1[1]=w22;
  res1[0]=(&w7);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @22) */
  arg1[0]=(&w9);
  arg1[1]=w22;
  res1[0]=(&w8);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @22) */
  arg1[0]=(&w10);
  arg1[1]=w22;
  res1[0]=(&w9);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @22) */
  arg1[0]=(&w11);
  arg1[1]=w22;
  res1[0]=(&w10);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @22) */
  arg1[0]=(&w12);
  arg1[1]=w22;
  res1[0]=(&w11);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @22) */
  arg1[0]=(&w13);
  arg1[1]=w22;
  res1[0]=(&w12);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @22) */
  arg1[0]=(&w14);
  arg1[1]=w22;
  res1[0]=(&w13);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @22) */
  arg1[0]=(&w15);
  arg1[1]=w22;
  res1[0]=(&w14);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @22) */
  arg1[0]=(&w16);
  arg1[1]=w22;
  res1[0]=(&w15);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @22) */
  arg1[0]=(&w17);
  arg1[1]=w22;
  res1[0]=(&w16);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @22) */
  arg1[0]=(&w18);
  arg1[1]=w22;
  res1[0]=(&w17);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @22) */
  arg1[0]=(&w19);
  arg1[1]=w22;
  res1[0]=(&w18);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @22) */
  arg1[0]=(&w20);
  arg1[1]=w22;
  res1[0]=(&w19);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #23: @20 = linear(@21, @22) */
  arg1[0]=(&w21);
  arg1[1]=w22;
  res1[0]=(&w20);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #24: @3 = horzcat(@23, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20) */
  rr=w3;
  *rr++ = w23;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  /* #25: @24 = sparse: 18-by-17, 34 nnz
   (0, 0) -> -30.6122
   (1, 0) -> 30.6122
   (1, 1) -> -29.4118
   (2, 1) -> 29.4118
   (2, 2) -> -15
   (3, 2) -> 15
   (3, 3) -> -15
   (4, 3) -> 15
   (4, 4) -> -15
   (5, 4) -> 15
   (5, 5) -> -15
   (6, 5) -> 15
   (6, 6) -> -15
   (7, 6) -> 15
   (7, 7) -> -15
   (8, 7) -> 15
   (8, 8) -> -15
   (9, 8) -> 15
   (9, 9) -> -15
   (10, 9) -> 15
   (10, 10) -> -15
   (11, 10) -> 15
   (11, 11) -> -15
   (12, 11) -> 15
   (12, 12) -> -15
   (13, 12) -> 15
   (13, 13) -> -15
   (14, 13) -> 15
   (14, 14) -> -15
   (15, 14) -> 15
   (15, 15) -> -29.4118
   (16, 15) -> 29.4118
   (16, 16) -> -30.6122
   (17, 16) -> 30.6122 */
  casadi_copy(casadi_c3, 34, w24);
  /* #26: @2 = mac(@3,@24,@2) */
  casadi_mtimes(w3, casadi_s8, w24, casadi_s7, w2, casadi_s6, w, 0);
  /* #27: @23 = BSplineParametric(@1) */
  casadi_clear((&w23), 1);
  CASADI_PREFIX(nd_boor_eval)((&w23),1,casadi_c4,casadi_s10,casadi_s9,casadi_s2,w2,1,(&w1),casadi_s0, iw, w);
  /* #28: (@0[0] = @23) */
  for (rr=w0+0, ss=(&w23); rr!=w0+1; rr+=1) *rr = *ss++;
  /* #29: output[0][0] = @0 */
  casadi_copy(w0, 7, res[0]);
  return 0;
}

/* jac_y:(x,c[6],out_f[1x1,0nz])->(jac[1x7]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_real **arg1=arg+3;
  casadi_real *w0=w+7, w1, *w2=w+15, *w3=w+32, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, *w22=w+68, w23, *w24=w+75;
  /* #0: @0 = zeros(7x1) */
  casadi_clear(w0, 7);
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = zeros(1x17) */
  casadi_clear(w2, 17);
  /* #3: @3 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w3);
  /* #4: {@4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21} = horzsplit(@3) */
  w4 = w3[0];
  w5 = w3[1];
  w6 = w3[2];
  w7 = w3[3];
  w8 = w3[4];
  w9 = w3[5];
  w10 = w3[6];
  w11 = w3[7];
  w12 = w3[8];
  w13 = w3[9];
  w14 = w3[10];
  w15 = w3[11];
  w16 = w3[12];
  w17 = w3[13];
  w18 = w3[14];
  w19 = w3[15];
  w20 = w3[16];
  w21 = w3[17];
  /* #5: @22 = input[1][0] */
  casadi_copy(arg[1], 6, w22);
  /* #6: @23 = linear(@4, @22) */
  arg1[0]=(&w4);
  arg1[1]=w22;
  res1[0]=(&w23);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @22) */
  arg1[0]=(&w5);
  arg1[1]=w22;
  res1[0]=(&w4);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @22) */
  arg1[0]=(&w6);
  arg1[1]=w22;
  res1[0]=(&w5);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @22) */
  arg1[0]=(&w7);
  arg1[1]=w22;
  res1[0]=(&w6);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @22) */
  arg1[0]=(&w8);
  arg1[1]=w22;
  res1[0]=(&w7);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @22) */
  arg1[0]=(&w9);
  arg1[1]=w22;
  res1[0]=(&w8);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @22) */
  arg1[0]=(&w10);
  arg1[1]=w22;
  res1[0]=(&w9);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @22) */
  arg1[0]=(&w11);
  arg1[1]=w22;
  res1[0]=(&w10);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @22) */
  arg1[0]=(&w12);
  arg1[1]=w22;
  res1[0]=(&w11);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @22) */
  arg1[0]=(&w13);
  arg1[1]=w22;
  res1[0]=(&w12);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @22) */
  arg1[0]=(&w14);
  arg1[1]=w22;
  res1[0]=(&w13);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @22) */
  arg1[0]=(&w15);
  arg1[1]=w22;
  res1[0]=(&w14);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @22) */
  arg1[0]=(&w16);
  arg1[1]=w22;
  res1[0]=(&w15);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @22) */
  arg1[0]=(&w17);
  arg1[1]=w22;
  res1[0]=(&w16);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @22) */
  arg1[0]=(&w18);
  arg1[1]=w22;
  res1[0]=(&w17);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @22) */
  arg1[0]=(&w19);
  arg1[1]=w22;
  res1[0]=(&w18);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @22) */
  arg1[0]=(&w20);
  arg1[1]=w22;
  res1[0]=(&w19);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #23: @20 = linear(@21, @22) */
  arg1[0]=(&w21);
  arg1[1]=w22;
  res1[0]=(&w20);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #24: @3 = horzcat(@23, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20) */
  rr=w3;
  *rr++ = w23;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  /* #25: @24 = sparse: 18-by-17, 34 nnz
   (0, 0) -> -30.6122
   (1, 0) -> 30.6122
   (1, 1) -> -29.4118
   (2, 1) -> 29.4118
   (2, 2) -> -15
   (3, 2) -> 15
   (3, 3) -> -15
   (4, 3) -> 15
   (4, 4) -> -15
   (5, 4) -> 15
   (5, 5) -> -15
   (6, 5) -> 15
   (6, 6) -> -15
   (7, 6) -> 15
   (7, 7) -> -15
   (8, 7) -> 15
   (8, 8) -> -15
   (9, 8) -> 15
   (9, 9) -> -15
   (10, 9) -> 15
   (10, 10) -> -15
   (11, 10) -> 15
   (11, 11) -> -15
   (12, 11) -> 15
   (12, 12) -> -15
   (13, 12) -> 15
   (13, 13) -> -15
   (14, 13) -> 15
   (14, 14) -> -15
   (15, 14) -> 15
   (15, 15) -> -29.4118
   (16, 15) -> 29.4118
   (16, 16) -> -30.6122
   (17, 16) -> 30.6122 */
  casadi_copy(casadi_c3, 34, w24);
  /* #26: @2 = mac(@3,@24,@2) */
  casadi_mtimes(w3, casadi_s8, w24, casadi_s7, w2, casadi_s6, w, 0);
  /* #27: @23 = BSplineParametric(@1) */
  casadi_clear((&w23), 1);
  CASADI_PREFIX(nd_boor_eval)((&w23),1,casadi_c4,casadi_s10,casadi_s9,casadi_s2,w2,1,(&w1),casadi_s0, iw, w);
  /* #28: (@0[0] = @23) */
  for (rr=w0+0, ss=(&w23); rr!=w0+1; rr+=1) *rr = *ss++;
  /* #29: output[0][0] = @0 */
  casadi_copy(w0, 7, res[0]);
  return 0;
}

/* fwd6_ode:(x[6],u[4],z[0],p[16],t[1x1,0nz],out_ode[6x1,0nz],out_alg[0],out_quad[0],fwd_x[6x6],fwd_u[4x6],fwd_z[0x6],fwd_p[16x6],fwd_t[1x6,0nz])->(fwd_ode[6x6],fwd_alg[0x6],fwd_quad[0x6]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+3, *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real **arg1=arg+13, *cs;
  casadi_real w0, w1, *w2=w+111, w3, w4, w5, w6, w7, w8, w9, *w10=w+122, w11, w12, w13, w14, w15, *w16=w+133, *w18=w+139, *w19=w+146, *w20=w+162, w21, w22, w23, *w24=w+172, w25, w26, w27, w28, w29, *w30=w+184, w31, w32, w33, w34, w35, *w36=w+196, w37, w38, w39, w40, w41, *w42=w+208, w43, w44, w45, w46, w47, *w48=w+220, *w49=w+227, w50, w51, w52, w53, w54, w55;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[9][0] */
  casadi_copy(arg[9], 4, w2);
  /* #3: {@3, @4, @5, @6} = vertsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[2];
  w6 = w2[3];
  /* #4: @7 = (@1*@3) */
  w7  = (w1*w3);
  /* #5: @8 = input[1][0] */
  w8 = arg[1] ? arg[1][0] : 0;
  /* #6: @9 = sin(@0) */
  w9 = sin( w0 );
  /* #7: @10 = input[8][0] */
  casadi_copy(arg[8], 6, w10);
  /* #8: {@11, @12, @13, @14, NULL, NULL} = vertsplit(@10) */
  w11 = w10[0];
  w12 = w10[1];
  w13 = w10[2];
  w14 = w10[3];
  /* #9: @15 = (@9*@13) */
  w15  = (w9*w13);
  /* #10: @15 = (@8*@15) */
  w15  = (w8*w15);
  /* #11: @7 = (@7-@15) */
  w7 -= w15;
  /* #12: output[0][0] = @7 */
  if (res[0]) res[0][0] = w7;
  /* #13: @7 = sin(@0) */
  w7 = sin( w0 );
  /* #14: @3 = (@7*@3) */
  w3  = (w7*w3);
  /* #15: @0 = cos(@0) */
  w0 = cos( w0 );
  /* #16: @13 = (@0*@13) */
  w13  = (w0*w13);
  /* #17: @13 = (@8*@13) */
  w13  = (w8*w13);
  /* #18: @3 = (@3+@13) */
  w3 += w13;
  /* #19: output[0][1] = @3 */
  if (res[0]) res[0][1] = w3;
  /* #20: output[0][2] = @4 */
  if (res[0]) res[0][2] = w4;
  /* #21: output[0][3] = @5 */
  if (res[0]) res[0][3] = w5;
  /* #22: output[0][4] = @6 */
  if (res[0]) res[0][4] = w6;
  /* #23: @6 = input[0][0] */
  w6 = arg[0] ? arg[0][0] : 0;
  /* #24: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #25: @4 = input[3][6] */
  w4 = arg[3] ? arg[3][10] : 0;
  /* #26: @10 = @4[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w10, ss=(&w4); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #27: @4 = x(@5, @10) */
  arg1[0]=(&w5);
  arg1[1]=w10;
  res1[0]=(&w4);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #28: @6 = (@6-@4) */
  w6 -= w4;
  /* #29: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #30: @16 = zeros(1x6) */
  casadi_clear(w16, 6);
  /* #31: @17 = 00 */
  /* #32: @18 = jac_x(@5, @10, @17) */
  arg1[0]=(&w5);
  arg1[1]=w10;
  arg1[2]=0;
  res1[0]=w18;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #33: @19 = input[11][0] */
  casadi_copy(arg[11], 16, w19);
  /* #34: {NULL, NULL, NULL, NULL, NULL, NULL, @4, @3, NULL, NULL, NULL, NULL} = vertsplit(@19) */
  w4 = w19[10];
  w3 = w19[11];
  /* #35: @10 = @4[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w10, ss=(&w4); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #36: @20 = vertcat(@14, @10) */
  rr=w20;
  *rr++ = w14;
  for (i=0, cs=w10; i<6; ++i) *rr++ = *cs++;
  /* #37: @10 = input[8][1] */
  casadi_copy(arg[8] ? arg[8]+6 : 0, 6, w10);
  /* #38: {@4, @13, @15, @21, NULL, NULL} = vertsplit(@10) */
  w4 = w10[0];
  w13 = w10[1];
  w15 = w10[2];
  w21 = w10[3];
  /* #39: @19 = input[11][1] */
  casadi_copy(arg[11] ? arg[11]+16 : 0, 16, w19);
  /* #40: {NULL, NULL, NULL, NULL, NULL, NULL, @22, @23, NULL, NULL, NULL, NULL} = vertsplit(@19) */
  w22 = w19[10];
  w23 = w19[11];
  /* #41: @10 = @22[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w10, ss=(&w22); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #42: @24 = vertcat(@21, @10) */
  rr=w24;
  *rr++ = w21;
  for (i=0, cs=w10; i<6; ++i) *rr++ = *cs++;
  /* #43: @10 = input[8][2] */
  casadi_copy(arg[8] ? arg[8]+12 : 0, 6, w10);
  /* #44: {@22, @25, @26, @27, NULL, NULL} = vertsplit(@10) */
  w22 = w10[0];
  w25 = w10[1];
  w26 = w10[2];
  w27 = w10[3];
  /* #45: @19 = input[11][2] */
  casadi_copy(arg[11] ? arg[11]+32 : 0, 16, w19);
  /* #46: {NULL, NULL, NULL, NULL, NULL, NULL, @28, @29, NULL, NULL, NULL, NULL} = vertsplit(@19) */
  w28 = w19[10];
  w29 = w19[11];
  /* #47: @10 = @28[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w10, ss=(&w28); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #48: @30 = vertcat(@27, @10) */
  rr=w30;
  *rr++ = w27;
  for (i=0, cs=w10; i<6; ++i) *rr++ = *cs++;
  /* #49: @10 = input[8][3] */
  casadi_copy(arg[8] ? arg[8]+18 : 0, 6, w10);
  /* #50: {@28, @31, @32, @33, NULL, NULL} = vertsplit(@10) */
  w28 = w10[0];
  w31 = w10[1];
  w32 = w10[2];
  w33 = w10[3];
  /* #51: @19 = input[11][3] */
  casadi_copy(arg[11] ? arg[11]+48 : 0, 16, w19);
  /* #52: {NULL, NULL, NULL, NULL, NULL, NULL, @34, @35, NULL, NULL, NULL, NULL} = vertsplit(@19) */
  w34 = w19[10];
  w35 = w19[11];
  /* #53: @10 = @34[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w10, ss=(&w34); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #54: @36 = vertcat(@33, @10) */
  rr=w36;
  *rr++ = w33;
  for (i=0, cs=w10; i<6; ++i) *rr++ = *cs++;
  /* #55: @10 = input[8][4] */
  casadi_copy(arg[8] ? arg[8]+24 : 0, 6, w10);
  /* #56: {@34, @37, @38, @39, NULL, NULL} = vertsplit(@10) */
  w34 = w10[0];
  w37 = w10[1];
  w38 = w10[2];
  w39 = w10[3];
  /* #57: @19 = input[11][4] */
  casadi_copy(arg[11] ? arg[11]+64 : 0, 16, w19);
  /* #58: {NULL, NULL, NULL, NULL, NULL, NULL, @40, @41, NULL, NULL, NULL, NULL} = vertsplit(@19) */
  w40 = w19[10];
  w41 = w19[11];
  /* #59: @10 = @40[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w10, ss=(&w40); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #60: @42 = vertcat(@39, @10) */
  rr=w42;
  *rr++ = w39;
  for (i=0, cs=w10; i<6; ++i) *rr++ = *cs++;
  /* #61: @10 = input[8][5] */
  casadi_copy(arg[8] ? arg[8]+30 : 0, 6, w10);
  /* #62: {@40, @43, @44, @45, NULL, NULL} = vertsplit(@10) */
  w40 = w10[0];
  w43 = w10[1];
  w44 = w10[2];
  w45 = w10[3];
  /* #63: @19 = input[11][5] */
  casadi_copy(arg[11] ? arg[11]+80 : 0, 16, w19);
  /* #64: {NULL, NULL, NULL, NULL, NULL, NULL, @46, @47, NULL, NULL, NULL, NULL} = vertsplit(@19) */
  w46 = w19[10];
  w47 = w19[11];
  /* #65: @10 = @46[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w10, ss=(&w46); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #66: @48 = vertcat(@45, @10) */
  rr=w48;
  *rr++ = w45;
  for (i=0, cs=w10; i<6; ++i) *rr++ = *cs++;
  /* #67: @49 = horzcat(@20, @24, @30, @36, @42, @48) */
  rr=w49;
  for (i=0, cs=w20; i<7; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<7; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<7; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<7; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<7; ++i) *rr++ = *cs++;
  for (i=0, cs=w48; i<7; ++i) *rr++ = *cs++;
  /* #68: @16 = mac(@18,@49,@16) */
  for (i=0, rr=w16; i<6; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w18+j, tt=w49+i*7; k<7; ++k) *rr += ss[k*1]**tt++;
  /* #69: {@46, @50, @51, @52, @53, @54} = horzsplit(@16) */
  w46 = w16[0];
  w50 = w16[1];
  w51 = w16[2];
  w52 = w16[3];
  w53 = w16[4];
  w54 = w16[5];
  /* #70: @11 = (@11-@46) */
  w11 -= w46;
  /* #71: @11 = (@6*@11) */
  w11  = (w6*w11);
  /* #72: @46 = input[0][1] */
  w46 = arg[0] ? arg[0][1] : 0;
  /* #73: @55 = input[3][7] */
  w55 = arg[3] ? arg[3][11] : 0;
  /* #74: @16 = @55[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w16, ss=(&w55); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #75: @55 = y(@5, @16) */
  arg1[0]=(&w5);
  arg1[1]=w16;
  res1[0]=(&w55);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #76: @46 = (@46-@55) */
  w46 -= w55;
  /* #77: @46 = (2.*@46) */
  w46 = (2.* w46 );
  /* #78: @10 = zeros(1x6) */
  casadi_clear(w10, 6);
  /* #79: @17 = 00 */
  /* #80: @18 = jac_y(@5, @16, @17) */
  arg1[0]=(&w5);
  arg1[1]=w16;
  arg1[2]=0;
  res1[0]=w18;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #81: @16 = @3[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w16, ss=(&w3); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #82: @20 = vertcat(@14, @16) */
  rr=w20;
  *rr++ = w14;
  for (i=0, cs=w16; i<6; ++i) *rr++ = *cs++;
  /* #83: @16 = @23[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w16, ss=(&w23); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #84: @24 = vertcat(@21, @16) */
  rr=w24;
  *rr++ = w21;
  for (i=0, cs=w16; i<6; ++i) *rr++ = *cs++;
  /* #85: @16 = @29[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w16, ss=(&w29); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #86: @30 = vertcat(@27, @16) */
  rr=w30;
  *rr++ = w27;
  for (i=0, cs=w16; i<6; ++i) *rr++ = *cs++;
  /* #87: @16 = @35[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w16, ss=(&w35); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #88: @36 = vertcat(@33, @16) */
  rr=w36;
  *rr++ = w33;
  for (i=0, cs=w16; i<6; ++i) *rr++ = *cs++;
  /* #89: @16 = @41[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w16, ss=(&w41); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #90: @42 = vertcat(@39, @16) */
  rr=w42;
  *rr++ = w39;
  for (i=0, cs=w16; i<6; ++i) *rr++ = *cs++;
  /* #91: @16 = @47[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w16, ss=(&w47); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #92: @48 = vertcat(@45, @16) */
  rr=w48;
  *rr++ = w45;
  for (i=0, cs=w16; i<6; ++i) *rr++ = *cs++;
  /* #93: @49 = horzcat(@20, @24, @30, @36, @42, @48) */
  rr=w49;
  for (i=0, cs=w20; i<7; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<7; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<7; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<7; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<7; ++i) *rr++ = *cs++;
  for (i=0, cs=w48; i<7; ++i) *rr++ = *cs++;
  /* #94: @10 = mac(@18,@49,@10) */
  for (i=0, rr=w10; i<6; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w18+j, tt=w49+i*7; k<7; ++k) *rr += ss[k*1]**tt++;
  /* #95: {@45, @47, @39, @41, @33, @35} = horzsplit(@10) */
  w45 = w10[0];
  w47 = w10[1];
  w39 = w10[2];
  w41 = w10[3];
  w33 = w10[4];
  w35 = w10[5];
  /* #96: @12 = (@12-@45) */
  w12 -= w45;
  /* #97: @12 = (@46*@12) */
  w12  = (w46*w12);
  /* #98: @11 = (@11+@12) */
  w11 += w12;
  /* #99: output[0][5] = @11 */
  if (res[0]) res[0][5] = w11;
  /* #100: @2 = input[9][1] */
  casadi_copy(arg[9] ? arg[9]+4 : 0, 4, w2);
  /* #101: {@11, @12, @45, @27} = vertsplit(@2) */
  w11 = w2[0];
  w12 = w2[1];
  w45 = w2[2];
  w27 = w2[3];
  /* #102: @29 = (@1*@11) */
  w29  = (w1*w11);
  /* #103: @21 = (@9*@15) */
  w21  = (w9*w15);
  /* #104: @21 = (@8*@21) */
  w21  = (w8*w21);
  /* #105: @29 = (@29-@21) */
  w29 -= w21;
  /* #106: output[0][6] = @29 */
  if (res[0]) res[0][6] = w29;
  /* #107: @11 = (@7*@11) */
  w11  = (w7*w11);
  /* #108: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #109: @15 = (@8*@15) */
  w15  = (w8*w15);
  /* #110: @11 = (@11+@15) */
  w11 += w15;
  /* #111: output[0][7] = @11 */
  if (res[0]) res[0][7] = w11;
  /* #112: output[0][8] = @12 */
  if (res[0]) res[0][8] = w12;
  /* #113: output[0][9] = @45 */
  if (res[0]) res[0][9] = w45;
  /* #114: output[0][10] = @27 */
  if (res[0]) res[0][10] = w27;
  /* #115: @4 = (@4-@50) */
  w4 -= w50;
  /* #116: @4 = (@6*@4) */
  w4  = (w6*w4);
  /* #117: @13 = (@13-@47) */
  w13 -= w47;
  /* #118: @13 = (@46*@13) */
  w13  = (w46*w13);
  /* #119: @4 = (@4+@13) */
  w4 += w13;
  /* #120: output[0][11] = @4 */
  if (res[0]) res[0][11] = w4;
  /* #121: @2 = input[9][2] */
  casadi_copy(arg[9] ? arg[9]+8 : 0, 4, w2);
  /* #122: {@4, @13, @47, @50} = vertsplit(@2) */
  w4 = w2[0];
  w13 = w2[1];
  w47 = w2[2];
  w50 = w2[3];
  /* #123: @27 = (@1*@4) */
  w27  = (w1*w4);
  /* #124: @45 = (@9*@26) */
  w45  = (w9*w26);
  /* #125: @45 = (@8*@45) */
  w45  = (w8*w45);
  /* #126: @27 = (@27-@45) */
  w27 -= w45;
  /* #127: output[0][12] = @27 */
  if (res[0]) res[0][12] = w27;
  /* #128: @4 = (@7*@4) */
  w4  = (w7*w4);
  /* #129: @26 = (@0*@26) */
  w26  = (w0*w26);
  /* #130: @26 = (@8*@26) */
  w26  = (w8*w26);
  /* #131: @4 = (@4+@26) */
  w4 += w26;
  /* #132: output[0][13] = @4 */
  if (res[0]) res[0][13] = w4;
  /* #133: output[0][14] = @13 */
  if (res[0]) res[0][14] = w13;
  /* #134: output[0][15] = @47 */
  if (res[0]) res[0][15] = w47;
  /* #135: output[0][16] = @50 */
  if (res[0]) res[0][16] = w50;
  /* #136: @22 = (@22-@51) */
  w22 -= w51;
  /* #137: @22 = (@6*@22) */
  w22  = (w6*w22);
  /* #138: @25 = (@25-@39) */
  w25 -= w39;
  /* #139: @25 = (@46*@25) */
  w25  = (w46*w25);
  /* #140: @22 = (@22+@25) */
  w22 += w25;
  /* #141: output[0][17] = @22 */
  if (res[0]) res[0][17] = w22;
  /* #142: @2 = input[9][3] */
  casadi_copy(arg[9] ? arg[9]+12 : 0, 4, w2);
  /* #143: {@22, @25, @39, @51} = vertsplit(@2) */
  w22 = w2[0];
  w25 = w2[1];
  w39 = w2[2];
  w51 = w2[3];
  /* #144: @50 = (@1*@22) */
  w50  = (w1*w22);
  /* #145: @47 = (@9*@32) */
  w47  = (w9*w32);
  /* #146: @47 = (@8*@47) */
  w47  = (w8*w47);
  /* #147: @50 = (@50-@47) */
  w50 -= w47;
  /* #148: output[0][18] = @50 */
  if (res[0]) res[0][18] = w50;
  /* #149: @22 = (@7*@22) */
  w22  = (w7*w22);
  /* #150: @32 = (@0*@32) */
  w32  = (w0*w32);
  /* #151: @32 = (@8*@32) */
  w32  = (w8*w32);
  /* #152: @22 = (@22+@32) */
  w22 += w32;
  /* #153: output[0][19] = @22 */
  if (res[0]) res[0][19] = w22;
  /* #154: output[0][20] = @25 */
  if (res[0]) res[0][20] = w25;
  /* #155: output[0][21] = @39 */
  if (res[0]) res[0][21] = w39;
  /* #156: output[0][22] = @51 */
  if (res[0]) res[0][22] = w51;
  /* #157: @28 = (@28-@52) */
  w28 -= w52;
  /* #158: @28 = (@6*@28) */
  w28  = (w6*w28);
  /* #159: @31 = (@31-@41) */
  w31 -= w41;
  /* #160: @31 = (@46*@31) */
  w31  = (w46*w31);
  /* #161: @28 = (@28+@31) */
  w28 += w31;
  /* #162: output[0][23] = @28 */
  if (res[0]) res[0][23] = w28;
  /* #163: @2 = input[9][4] */
  casadi_copy(arg[9] ? arg[9]+16 : 0, 4, w2);
  /* #164: {@28, @31, @41, @52} = vertsplit(@2) */
  w28 = w2[0];
  w31 = w2[1];
  w41 = w2[2];
  w52 = w2[3];
  /* #165: @51 = (@1*@28) */
  w51  = (w1*w28);
  /* #166: @39 = (@9*@38) */
  w39  = (w9*w38);
  /* #167: @39 = (@8*@39) */
  w39  = (w8*w39);
  /* #168: @51 = (@51-@39) */
  w51 -= w39;
  /* #169: output[0][24] = @51 */
  if (res[0]) res[0][24] = w51;
  /* #170: @28 = (@7*@28) */
  w28  = (w7*w28);
  /* #171: @38 = (@0*@38) */
  w38  = (w0*w38);
  /* #172: @38 = (@8*@38) */
  w38  = (w8*w38);
  /* #173: @28 = (@28+@38) */
  w28 += w38;
  /* #174: output[0][25] = @28 */
  if (res[0]) res[0][25] = w28;
  /* #175: output[0][26] = @31 */
  if (res[0]) res[0][26] = w31;
  /* #176: output[0][27] = @41 */
  if (res[0]) res[0][27] = w41;
  /* #177: output[0][28] = @52 */
  if (res[0]) res[0][28] = w52;
  /* #178: @34 = (@34-@53) */
  w34 -= w53;
  /* #179: @34 = (@6*@34) */
  w34  = (w6*w34);
  /* #180: @37 = (@37-@33) */
  w37 -= w33;
  /* #181: @37 = (@46*@37) */
  w37  = (w46*w37);
  /* #182: @34 = (@34+@37) */
  w34 += w37;
  /* #183: output[0][29] = @34 */
  if (res[0]) res[0][29] = w34;
  /* #184: @2 = input[9][5] */
  casadi_copy(arg[9] ? arg[9]+20 : 0, 4, w2);
  /* #185: {@34, @37, @33, @53} = vertsplit(@2) */
  w34 = w2[0];
  w37 = w2[1];
  w33 = w2[2];
  w53 = w2[3];
  /* #186: @1 = (@1*@34) */
  w1 *= w34;
  /* #187: @9 = (@9*@44) */
  w9 *= w44;
  /* #188: @9 = (@8*@9) */
  w9  = (w8*w9);
  /* #189: @1 = (@1-@9) */
  w1 -= w9;
  /* #190: output[0][30] = @1 */
  if (res[0]) res[0][30] = w1;
  /* #191: @7 = (@7*@34) */
  w7 *= w34;
  /* #192: @0 = (@0*@44) */
  w0 *= w44;
  /* #193: @8 = (@8*@0) */
  w8 *= w0;
  /* #194: @7 = (@7+@8) */
  w7 += w8;
  /* #195: output[0][31] = @7 */
  if (res[0]) res[0][31] = w7;
  /* #196: output[0][32] = @37 */
  if (res[0]) res[0][32] = w37;
  /* #197: output[0][33] = @33 */
  if (res[0]) res[0][33] = w33;
  /* #198: output[0][34] = @53 */
  if (res[0]) res[0][34] = w53;
  /* #199: @40 = (@40-@54) */
  w40 -= w54;
  /* #200: @6 = (@6*@40) */
  w6 *= w40;
  /* #201: @43 = (@43-@35) */
  w43 -= w35;
  /* #202: @46 = (@46*@43) */
  w46 *= w43;
  /* #203: @6 = (@6+@46) */
  w6 += w46;
  /* #204: output[0][35] = @6 */
  if (res[0]) res[0][35] = w6;
  return 0;
}

/* fwd1_x:(x,c[6],out_f[1x1,0nz],fwd_x,fwd_c[6])->(fwd_f) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+5;
  casadi_real w0, *w1=w+8, *w2=w+25, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+61, w22, *w23=w+68;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x17) */
  casadi_clear(w1, 17);
  /* #2: @2 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w2);
  /* #3: {@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20} = horzsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[2];
  w6 = w2[3];
  w7 = w2[4];
  w8 = w2[5];
  w9 = w2[6];
  w10 = w2[7];
  w11 = w2[8];
  w12 = w2[9];
  w13 = w2[10];
  w14 = w2[11];
  w15 = w2[12];
  w16 = w2[13];
  w17 = w2[14];
  w18 = w2[15];
  w19 = w2[16];
  w20 = w2[17];
  /* #4: @21 = input[1][0] */
  casadi_copy(arg[1], 6, w21);
  /* #5: @22 = linear(@3, @21) */
  arg1[0]=(&w3);
  arg1[1]=w21;
  res1[0]=(&w22);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @21) */
  arg1[0]=(&w4);
  arg1[1]=w21;
  res1[0]=(&w3);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @21) */
  arg1[0]=(&w5);
  arg1[1]=w21;
  res1[0]=(&w4);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @21) */
  arg1[0]=(&w6);
  arg1[1]=w21;
  res1[0]=(&w5);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @21) */
  arg1[0]=(&w7);
  arg1[1]=w21;
  res1[0]=(&w6);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @21) */
  arg1[0]=(&w8);
  arg1[1]=w21;
  res1[0]=(&w7);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @21) */
  arg1[0]=(&w9);
  arg1[1]=w21;
  res1[0]=(&w8);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @21) */
  arg1[0]=(&w10);
  arg1[1]=w21;
  res1[0]=(&w9);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @21) */
  arg1[0]=(&w11);
  arg1[1]=w21;
  res1[0]=(&w10);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @21) */
  arg1[0]=(&w12);
  arg1[1]=w21;
  res1[0]=(&w11);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @21) */
  arg1[0]=(&w13);
  arg1[1]=w21;
  res1[0]=(&w12);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @21) */
  arg1[0]=(&w14);
  arg1[1]=w21;
  res1[0]=(&w13);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @21) */
  arg1[0]=(&w15);
  arg1[1]=w21;
  res1[0]=(&w14);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @21) */
  arg1[0]=(&w16);
  arg1[1]=w21;
  res1[0]=(&w15);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @21) */
  arg1[0]=(&w17);
  arg1[1]=w21;
  res1[0]=(&w16);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @21) */
  arg1[0]=(&w18);
  arg1[1]=w21;
  res1[0]=(&w17);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @21) */
  arg1[0]=(&w19);
  arg1[1]=w21;
  res1[0]=(&w18);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @21) */
  arg1[0]=(&w20);
  arg1[1]=w21;
  res1[0]=(&w19);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #23: @2 = horzcat(@22, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w2;
  *rr++ = w22;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  /* #24: @23 = sparse: 18-by-17, 34 nnz
   (0, 0) -> -30.6122
   (1, 0) -> 30.6122
   (1, 1) -> -29.4118
   (2, 1) -> 29.4118
   (2, 2) -> -15
   (3, 2) -> 15
   (3, 3) -> -15
   (4, 3) -> 15
   (4, 4) -> -15
   (5, 4) -> 15
   (5, 5) -> -15
   (6, 5) -> 15
   (6, 6) -> -15
   (7, 6) -> 15
   (7, 7) -> -15
   (8, 7) -> 15
   (8, 8) -> -15
   (9, 8) -> 15
   (9, 9) -> -15
   (10, 9) -> 15
   (10, 10) -> -15
   (11, 10) -> 15
   (11, 11) -> -15
   (12, 11) -> 15
   (12, 12) -> -15
   (13, 12) -> 15
   (13, 13) -> -15
   (14, 13) -> 15
   (14, 14) -> -15
   (15, 14) -> 15
   (15, 15) -> -29.4118
   (16, 15) -> 29.4118
   (16, 16) -> -30.6122
   (17, 16) -> 30.6122 */
  casadi_copy(casadi_c3, 34, w23);
  /* #25: @1 = mac(@2,@23,@1) */
  casadi_mtimes(w2, casadi_s8, w23, casadi_s7, w1, casadi_s6, w, 0);
  /* #26: @22 = BSplineParametric(@0) */
  casadi_clear((&w22), 1);
  CASADI_PREFIX(nd_boor_eval)((&w22),1,casadi_c4,casadi_s10,casadi_s9,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #27: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #28: @22 = (@22*@0) */
  w22 *= w0;
  /* #29: output[0][0] = @22 */
  if (res[0]) res[0][0] = w22;
  return 0;
}

/* fwd1_y:(x,c[6],out_f[1x1,0nz],fwd_x,fwd_c[6])->(fwd_f) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+5;
  casadi_real w0, *w1=w+8, *w2=w+25, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+61, w22, *w23=w+68;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x17) */
  casadi_clear(w1, 17);
  /* #2: @2 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w2);
  /* #3: {@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20} = horzsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[2];
  w6 = w2[3];
  w7 = w2[4];
  w8 = w2[5];
  w9 = w2[6];
  w10 = w2[7];
  w11 = w2[8];
  w12 = w2[9];
  w13 = w2[10];
  w14 = w2[11];
  w15 = w2[12];
  w16 = w2[13];
  w17 = w2[14];
  w18 = w2[15];
  w19 = w2[16];
  w20 = w2[17];
  /* #4: @21 = input[1][0] */
  casadi_copy(arg[1], 6, w21);
  /* #5: @22 = linear(@3, @21) */
  arg1[0]=(&w3);
  arg1[1]=w21;
  res1[0]=(&w22);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @21) */
  arg1[0]=(&w4);
  arg1[1]=w21;
  res1[0]=(&w3);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @21) */
  arg1[0]=(&w5);
  arg1[1]=w21;
  res1[0]=(&w4);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @21) */
  arg1[0]=(&w6);
  arg1[1]=w21;
  res1[0]=(&w5);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @21) */
  arg1[0]=(&w7);
  arg1[1]=w21;
  res1[0]=(&w6);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @21) */
  arg1[0]=(&w8);
  arg1[1]=w21;
  res1[0]=(&w7);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @21) */
  arg1[0]=(&w9);
  arg1[1]=w21;
  res1[0]=(&w8);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @21) */
  arg1[0]=(&w10);
  arg1[1]=w21;
  res1[0]=(&w9);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @21) */
  arg1[0]=(&w11);
  arg1[1]=w21;
  res1[0]=(&w10);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @21) */
  arg1[0]=(&w12);
  arg1[1]=w21;
  res1[0]=(&w11);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @21) */
  arg1[0]=(&w13);
  arg1[1]=w21;
  res1[0]=(&w12);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @21) */
  arg1[0]=(&w14);
  arg1[1]=w21;
  res1[0]=(&w13);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @21) */
  arg1[0]=(&w15);
  arg1[1]=w21;
  res1[0]=(&w14);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @21) */
  arg1[0]=(&w16);
  arg1[1]=w21;
  res1[0]=(&w15);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @21) */
  arg1[0]=(&w17);
  arg1[1]=w21;
  res1[0]=(&w16);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @21) */
  arg1[0]=(&w18);
  arg1[1]=w21;
  res1[0]=(&w17);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @21) */
  arg1[0]=(&w19);
  arg1[1]=w21;
  res1[0]=(&w18);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @21) */
  arg1[0]=(&w20);
  arg1[1]=w21;
  res1[0]=(&w19);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #23: @2 = horzcat(@22, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w2;
  *rr++ = w22;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  /* #24: @23 = sparse: 18-by-17, 34 nnz
   (0, 0) -> -30.6122
   (1, 0) -> 30.6122
   (1, 1) -> -29.4118
   (2, 1) -> 29.4118
   (2, 2) -> -15
   (3, 2) -> 15
   (3, 3) -> -15
   (4, 3) -> 15
   (4, 4) -> -15
   (5, 4) -> 15
   (5, 5) -> -15
   (6, 5) -> 15
   (6, 6) -> -15
   (7, 6) -> 15
   (7, 7) -> -15
   (8, 7) -> 15
   (8, 8) -> -15
   (9, 8) -> 15
   (9, 9) -> -15
   (10, 9) -> 15
   (10, 10) -> -15
   (11, 10) -> 15
   (11, 11) -> -15
   (12, 11) -> 15
   (12, 12) -> -15
   (13, 12) -> 15
   (13, 13) -> -15
   (14, 13) -> 15
   (14, 14) -> -15
   (15, 14) -> 15
   (15, 15) -> -29.4118
   (16, 15) -> 29.4118
   (16, 16) -> -30.6122
   (17, 16) -> 30.6122 */
  casadi_copy(casadi_c3, 34, w23);
  /* #25: @1 = mac(@2,@23,@1) */
  casadi_mtimes(w2, casadi_s8, w23, casadi_s7, w1, casadi_s6, w, 0);
  /* #26: @22 = BSplineParametric(@0) */
  casadi_clear((&w22), 1);
  CASADI_PREFIX(nd_boor_eval)((&w22),1,casadi_c4,casadi_s10,casadi_s9,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #27: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #28: @22 = (@22*@0) */
  w22 *= w0;
  /* #29: output[0][0] = @22 */
  if (res[0]) res[0][0] = w22;
  return 0;
}

/* fwd1_ode:(x[6],u[4],z[0],p[16],t[1x1,0nz],out_ode[6x1,0nz],out_alg[0],out_quad[0],fwd_x[6],fwd_u[4],fwd_z[0],fwd_p[16],fwd_t[1x1,0nz])->(fwd_ode[6],fwd_alg[0],fwd_quad[0]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+3, *rr, *ss;
  const casadi_int *cii;
  const casadi_real **arg1=arg+13;
  casadi_real w0, w1, *w2=w+104, w3, w4, w5, w6, w7, w8, *w9=w+114, w10, w11, w12, w13, *w15=w+124, *w16=w+140;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[9][0] */
  casadi_copy(arg[9], 4, w2);
  /* #3: {@3, @4, @5, @6} = vertsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[2];
  w6 = w2[3];
  /* #4: @1 = (@1*@3) */
  w1 *= w3;
  /* #5: @7 = input[1][0] */
  w7 = arg[1] ? arg[1][0] : 0;
  /* #6: @8 = sin(@0) */
  w8 = sin( w0 );
  /* #7: @9 = input[8][0] */
  casadi_copy(arg[8], 6, w9);
  /* #8: {@10, @11, @12, @13, NULL, NULL} = vertsplit(@9) */
  w10 = w9[0];
  w11 = w9[1];
  w12 = w9[2];
  w13 = w9[3];
  /* #9: @8 = (@8*@12) */
  w8 *= w12;
  /* #10: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #11: @1 = (@1-@8) */
  w1 -= w8;
  /* #12: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #13: @1 = sin(@0) */
  w1 = sin( w0 );
  /* #14: @1 = (@1*@3) */
  w1 *= w3;
  /* #15: @0 = cos(@0) */
  w0 = cos( w0 );
  /* #16: @0 = (@0*@12) */
  w0 *= w12;
  /* #17: @7 = (@7*@0) */
  w7 *= w0;
  /* #18: @1 = (@1+@7) */
  w1 += w7;
  /* #19: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #20: output[0][2] = @4 */
  if (res[0]) res[0][2] = w4;
  /* #21: output[0][3] = @5 */
  if (res[0]) res[0][3] = w5;
  /* #22: output[0][4] = @6 */
  if (res[0]) res[0][4] = w6;
  /* #23: @6 = input[0][0] */
  w6 = arg[0] ? arg[0][0] : 0;
  /* #24: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #25: @4 = input[3][6] */
  w4 = arg[3] ? arg[3][10] : 0;
  /* #26: @9 = @4[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w9, ss=(&w4); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #27: @4 = x(@5, @9) */
  arg1[0]=(&w5);
  arg1[1]=w9;
  res1[0]=(&w4);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #28: @6 = (@6-@4) */
  w6 -= w4;
  /* #29: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #30: @14 = 00 */
  /* #31: @15 = input[11][0] */
  casadi_copy(arg[11], 16, w15);
  /* #32: {NULL, NULL, NULL, NULL, NULL, NULL, @4, @1, NULL, NULL, NULL, NULL} = vertsplit(@15) */
  w4 = w15[10];
  w1 = w15[11];
  /* #33: @16 = @4[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w16, ss=(&w4); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #34: @4 = fwd1_x(@5, @9, @14, @13, @16) */
  arg1[0]=(&w5);
  arg1[1]=w9;
  arg1[2]=0;
  arg1[3]=(&w13);
  arg1[4]=w16;
  res1[0]=(&w4);
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #35: @10 = (@10-@4) */
  w10 -= w4;
  /* #36: @6 = (@6*@10) */
  w6 *= w10;
  /* #37: @10 = input[0][1] */
  w10 = arg[0] ? arg[0][1] : 0;
  /* #38: @4 = input[3][7] */
  w4 = arg[3] ? arg[3][11] : 0;
  /* #39: @9 = @4[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w9, ss=(&w4); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #40: @4 = y(@5, @9) */
  arg1[0]=(&w5);
  arg1[1]=w9;
  res1[0]=(&w4);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #41: @10 = (@10-@4) */
  w10 -= w4;
  /* #42: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #43: @14 = 00 */
  /* #44: @16 = @1[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w16, ss=(&w1); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #45: @1 = fwd1_y(@5, @9, @14, @13, @16) */
  arg1[0]=(&w5);
  arg1[1]=w9;
  arg1[2]=0;
  arg1[3]=(&w13);
  arg1[4]=w16;
  res1[0]=(&w1);
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #46: @11 = (@11-@1) */
  w11 -= w1;
  /* #47: @10 = (@10*@11) */
  w10 *= w11;
  /* #48: @6 = (@6+@10) */
  w6 += w10;
  /* #49: output[0][5] = @6 */
  if (res[0]) res[0][5] = w6;
  return 0;
}

/* fwd4_x:(x,c[6],out_f[1x1,0nz],fwd_x[1x4],fwd_c[6x4])->(fwd_f[1x4]) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+5;
  casadi_real w0, *w1=w+8, *w2=w+25, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+61, w22, *w23=w+68;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x17) */
  casadi_clear(w1, 17);
  /* #2: @2 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w2);
  /* #3: {@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20} = horzsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[2];
  w6 = w2[3];
  w7 = w2[4];
  w8 = w2[5];
  w9 = w2[6];
  w10 = w2[7];
  w11 = w2[8];
  w12 = w2[9];
  w13 = w2[10];
  w14 = w2[11];
  w15 = w2[12];
  w16 = w2[13];
  w17 = w2[14];
  w18 = w2[15];
  w19 = w2[16];
  w20 = w2[17];
  /* #4: @21 = input[1][0] */
  casadi_copy(arg[1], 6, w21);
  /* #5: @22 = linear(@3, @21) */
  arg1[0]=(&w3);
  arg1[1]=w21;
  res1[0]=(&w22);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @21) */
  arg1[0]=(&w4);
  arg1[1]=w21;
  res1[0]=(&w3);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @21) */
  arg1[0]=(&w5);
  arg1[1]=w21;
  res1[0]=(&w4);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @21) */
  arg1[0]=(&w6);
  arg1[1]=w21;
  res1[0]=(&w5);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @21) */
  arg1[0]=(&w7);
  arg1[1]=w21;
  res1[0]=(&w6);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @21) */
  arg1[0]=(&w8);
  arg1[1]=w21;
  res1[0]=(&w7);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @21) */
  arg1[0]=(&w9);
  arg1[1]=w21;
  res1[0]=(&w8);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @21) */
  arg1[0]=(&w10);
  arg1[1]=w21;
  res1[0]=(&w9);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @21) */
  arg1[0]=(&w11);
  arg1[1]=w21;
  res1[0]=(&w10);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @21) */
  arg1[0]=(&w12);
  arg1[1]=w21;
  res1[0]=(&w11);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @21) */
  arg1[0]=(&w13);
  arg1[1]=w21;
  res1[0]=(&w12);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @21) */
  arg1[0]=(&w14);
  arg1[1]=w21;
  res1[0]=(&w13);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @21) */
  arg1[0]=(&w15);
  arg1[1]=w21;
  res1[0]=(&w14);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @21) */
  arg1[0]=(&w16);
  arg1[1]=w21;
  res1[0]=(&w15);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @21) */
  arg1[0]=(&w17);
  arg1[1]=w21;
  res1[0]=(&w16);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @21) */
  arg1[0]=(&w18);
  arg1[1]=w21;
  res1[0]=(&w17);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @21) */
  arg1[0]=(&w19);
  arg1[1]=w21;
  res1[0]=(&w18);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @21) */
  arg1[0]=(&w20);
  arg1[1]=w21;
  res1[0]=(&w19);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #23: @2 = horzcat(@22, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w2;
  *rr++ = w22;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  /* #24: @23 = sparse: 18-by-17, 34 nnz
   (0, 0) -> -30.6122
   (1, 0) -> 30.6122
   (1, 1) -> -29.4118
   (2, 1) -> 29.4118
   (2, 2) -> -15
   (3, 2) -> 15
   (3, 3) -> -15
   (4, 3) -> 15
   (4, 4) -> -15
   (5, 4) -> 15
   (5, 5) -> -15
   (6, 5) -> 15
   (6, 6) -> -15
   (7, 6) -> 15
   (7, 7) -> -15
   (8, 7) -> 15
   (8, 8) -> -15
   (9, 8) -> 15
   (9, 9) -> -15
   (10, 9) -> 15
   (10, 10) -> -15
   (11, 10) -> 15
   (11, 11) -> -15
   (12, 11) -> 15
   (12, 12) -> -15
   (13, 12) -> 15
   (13, 13) -> -15
   (14, 13) -> 15
   (14, 14) -> -15
   (15, 14) -> 15
   (15, 15) -> -29.4118
   (16, 15) -> 29.4118
   (16, 16) -> -30.6122
   (17, 16) -> 30.6122 */
  casadi_copy(casadi_c3, 34, w23);
  /* #25: @1 = mac(@2,@23,@1) */
  casadi_mtimes(w2, casadi_s8, w23, casadi_s7, w1, casadi_s6, w, 0);
  /* #26: @22 = BSplineParametric(@0) */
  casadi_clear((&w22), 1);
  CASADI_PREFIX(nd_boor_eval)((&w22),1,casadi_c4,casadi_s10,casadi_s9,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #27: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #28: @0 = (@22*@0) */
  w0  = (w22*w0);
  /* #29: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #30: @0 = input[3][1] */
  w0 = arg[3] ? arg[3][1] : 0;
  /* #31: @0 = (@22*@0) */
  w0  = (w22*w0);
  /* #32: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #33: @0 = input[3][2] */
  w0 = arg[3] ? arg[3][2] : 0;
  /* #34: @0 = (@22*@0) */
  w0  = (w22*w0);
  /* #35: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #36: @0 = input[3][3] */
  w0 = arg[3] ? arg[3][3] : 0;
  /* #37: @22 = (@22*@0) */
  w22 *= w0;
  /* #38: output[0][3] = @22 */
  if (res[0]) res[0][3] = w22;
  return 0;
}

/* fwd4_y:(x,c[6],out_f[1x1,0nz],fwd_x[1x4],fwd_c[6x4])->(fwd_f[1x4]) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+5;
  casadi_real w0, *w1=w+8, *w2=w+25, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+61, w22, *w23=w+68;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x17) */
  casadi_clear(w1, 17);
  /* #2: @2 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w2);
  /* #3: {@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20} = horzsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[2];
  w6 = w2[3];
  w7 = w2[4];
  w8 = w2[5];
  w9 = w2[6];
  w10 = w2[7];
  w11 = w2[8];
  w12 = w2[9];
  w13 = w2[10];
  w14 = w2[11];
  w15 = w2[12];
  w16 = w2[13];
  w17 = w2[14];
  w18 = w2[15];
  w19 = w2[16];
  w20 = w2[17];
  /* #4: @21 = input[1][0] */
  casadi_copy(arg[1], 6, w21);
  /* #5: @22 = linear(@3, @21) */
  arg1[0]=(&w3);
  arg1[1]=w21;
  res1[0]=(&w22);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @21) */
  arg1[0]=(&w4);
  arg1[1]=w21;
  res1[0]=(&w3);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @21) */
  arg1[0]=(&w5);
  arg1[1]=w21;
  res1[0]=(&w4);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @21) */
  arg1[0]=(&w6);
  arg1[1]=w21;
  res1[0]=(&w5);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @21) */
  arg1[0]=(&w7);
  arg1[1]=w21;
  res1[0]=(&w6);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @21) */
  arg1[0]=(&w8);
  arg1[1]=w21;
  res1[0]=(&w7);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @21) */
  arg1[0]=(&w9);
  arg1[1]=w21;
  res1[0]=(&w8);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @21) */
  arg1[0]=(&w10);
  arg1[1]=w21;
  res1[0]=(&w9);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @21) */
  arg1[0]=(&w11);
  arg1[1]=w21;
  res1[0]=(&w10);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @21) */
  arg1[0]=(&w12);
  arg1[1]=w21;
  res1[0]=(&w11);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @21) */
  arg1[0]=(&w13);
  arg1[1]=w21;
  res1[0]=(&w12);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @21) */
  arg1[0]=(&w14);
  arg1[1]=w21;
  res1[0]=(&w13);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @21) */
  arg1[0]=(&w15);
  arg1[1]=w21;
  res1[0]=(&w14);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @21) */
  arg1[0]=(&w16);
  arg1[1]=w21;
  res1[0]=(&w15);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @21) */
  arg1[0]=(&w17);
  arg1[1]=w21;
  res1[0]=(&w16);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @21) */
  arg1[0]=(&w18);
  arg1[1]=w21;
  res1[0]=(&w17);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @21) */
  arg1[0]=(&w19);
  arg1[1]=w21;
  res1[0]=(&w18);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @21) */
  arg1[0]=(&w20);
  arg1[1]=w21;
  res1[0]=(&w19);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #23: @2 = horzcat(@22, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w2;
  *rr++ = w22;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  /* #24: @23 = sparse: 18-by-17, 34 nnz
   (0, 0) -> -30.6122
   (1, 0) -> 30.6122
   (1, 1) -> -29.4118
   (2, 1) -> 29.4118
   (2, 2) -> -15
   (3, 2) -> 15
   (3, 3) -> -15
   (4, 3) -> 15
   (4, 4) -> -15
   (5, 4) -> 15
   (5, 5) -> -15
   (6, 5) -> 15
   (6, 6) -> -15
   (7, 6) -> 15
   (7, 7) -> -15
   (8, 7) -> 15
   (8, 8) -> -15
   (9, 8) -> 15
   (9, 9) -> -15
   (10, 9) -> 15
   (10, 10) -> -15
   (11, 10) -> 15
   (11, 11) -> -15
   (12, 11) -> 15
   (12, 12) -> -15
   (13, 12) -> 15
   (13, 13) -> -15
   (14, 13) -> 15
   (14, 14) -> -15
   (15, 14) -> 15
   (15, 15) -> -29.4118
   (16, 15) -> 29.4118
   (16, 16) -> -30.6122
   (17, 16) -> 30.6122 */
  casadi_copy(casadi_c3, 34, w23);
  /* #25: @1 = mac(@2,@23,@1) */
  casadi_mtimes(w2, casadi_s8, w23, casadi_s7, w1, casadi_s6, w, 0);
  /* #26: @22 = BSplineParametric(@0) */
  casadi_clear((&w22), 1);
  CASADI_PREFIX(nd_boor_eval)((&w22),1,casadi_c4,casadi_s10,casadi_s9,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #27: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #28: @0 = (@22*@0) */
  w0  = (w22*w0);
  /* #29: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #30: @0 = input[3][1] */
  w0 = arg[3] ? arg[3][1] : 0;
  /* #31: @0 = (@22*@0) */
  w0  = (w22*w0);
  /* #32: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #33: @0 = input[3][2] */
  w0 = arg[3] ? arg[3][2] : 0;
  /* #34: @0 = (@22*@0) */
  w0  = (w22*w0);
  /* #35: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #36: @0 = input[3][3] */
  w0 = arg[3] ? arg[3][3] : 0;
  /* #37: @22 = (@22*@0) */
  w22 *= w0;
  /* #38: output[0][3] = @22 */
  if (res[0]) res[0][3] = w22;
  return 0;
}

/* fwd4_ode:(x[6],u[4],z[0],p[16],t[1x1,0nz],out_ode[6x1,0nz],out_alg[0],out_quad[0],fwd_x[6x4],fwd_u[4x4],fwd_z[0x4],fwd_p[16x4],fwd_t[1x4,0nz])->(fwd_ode[6x4],fwd_alg[0x4],fwd_quad[0x4]) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+3, *rr, *ss;
  const casadi_int *cii;
  const casadi_real **arg1=arg+13, *cs;
  casadi_real w0, w1, *w2=w+104, w3, w4, w5, w6, w7, w8, w9, *w10=w+115, w11, w12, w13, w14, w15, *w17=w+126, w18, w19, w20, w21, w22, w23, w24, w25, *w26=w+140, w27, w28, w29, *w30=w+159, w31, *w32=w+166, w33, *w34=w+173, *w35=w+179, *w36=w+203, w37, w38, w39, w40;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[9][0] */
  casadi_copy(arg[9], 4, w2);
  /* #3: {@3, @4, @5, @6} = vertsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[2];
  w6 = w2[3];
  /* #4: @7 = (@1*@3) */
  w7  = (w1*w3);
  /* #5: @8 = input[1][0] */
  w8 = arg[1] ? arg[1][0] : 0;
  /* #6: @9 = sin(@0) */
  w9 = sin( w0 );
  /* #7: @10 = input[8][0] */
  casadi_copy(arg[8], 6, w10);
  /* #8: {@11, @12, @13, @14, NULL, NULL} = vertsplit(@10) */
  w11 = w10[0];
  w12 = w10[1];
  w13 = w10[2];
  w14 = w10[3];
  /* #9: @15 = (@9*@13) */
  w15  = (w9*w13);
  /* #10: @15 = (@8*@15) */
  w15  = (w8*w15);
  /* #11: @7 = (@7-@15) */
  w7 -= w15;
  /* #12: output[0][0] = @7 */
  if (res[0]) res[0][0] = w7;
  /* #13: @7 = sin(@0) */
  w7 = sin( w0 );
  /* #14: @3 = (@7*@3) */
  w3  = (w7*w3);
  /* #15: @0 = cos(@0) */
  w0 = cos( w0 );
  /* #16: @13 = (@0*@13) */
  w13  = (w0*w13);
  /* #17: @13 = (@8*@13) */
  w13  = (w8*w13);
  /* #18: @3 = (@3+@13) */
  w3 += w13;
  /* #19: output[0][1] = @3 */
  if (res[0]) res[0][1] = w3;
  /* #20: output[0][2] = @4 */
  if (res[0]) res[0][2] = w4;
  /* #21: output[0][3] = @5 */
  if (res[0]) res[0][3] = w5;
  /* #22: output[0][4] = @6 */
  if (res[0]) res[0][4] = w6;
  /* #23: @6 = input[0][0] */
  w6 = arg[0] ? arg[0][0] : 0;
  /* #24: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #25: @4 = input[3][6] */
  w4 = arg[3] ? arg[3][10] : 0;
  /* #26: @10 = @4[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w10, ss=(&w4); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #27: @4 = x(@5, @10) */
  arg1[0]=(&w5);
  arg1[1]=w10;
  res1[0]=(&w4);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #28: @6 = (@6-@4) */
  w6 -= w4;
  /* #29: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #30: @16 = 00 */
  /* #31: @17 = input[8][1] */
  casadi_copy(arg[8] ? arg[8]+6 : 0, 6, w17);
  /* #32: {@4, @3, @13, @15, NULL, NULL} = vertsplit(@17) */
  w4 = w17[0];
  w3 = w17[1];
  w13 = w17[2];
  w15 = w17[3];
  /* #33: @17 = input[8][2] */
  casadi_copy(arg[8] ? arg[8]+12 : 0, 6, w17);
  /* #34: {@18, @19, @20, @21, NULL, NULL} = vertsplit(@17) */
  w18 = w17[0];
  w19 = w17[1];
  w20 = w17[2];
  w21 = w17[3];
  /* #35: @17 = input[8][3] */
  casadi_copy(arg[8] ? arg[8]+18 : 0, 6, w17);
  /* #36: {@22, @23, @24, @25, NULL, NULL} = vertsplit(@17) */
  w22 = w17[0];
  w23 = w17[1];
  w24 = w17[2];
  w25 = w17[3];
  /* #37: @2 = horzcat(@14, @15, @21, @25) */
  rr=w2;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w21;
  *rr++ = w25;
  /* #38: @26 = input[11][0] */
  casadi_copy(arg[11], 16, w26);
  /* #39: {NULL, NULL, NULL, NULL, NULL, NULL, @27, @28, NULL, NULL, NULL, NULL} = vertsplit(@26) */
  w27 = w26[10];
  w28 = w26[11];
  /* #40: @17 = @27[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w17, ss=(&w27); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #41: @26 = input[11][1] */
  casadi_copy(arg[11] ? arg[11]+16 : 0, 16, w26);
  /* #42: {NULL, NULL, NULL, NULL, NULL, NULL, @27, @29, NULL, NULL, NULL, NULL} = vertsplit(@26) */
  w27 = w26[10];
  w29 = w26[11];
  /* #43: @30 = @27[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w30, ss=(&w27); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #44: @26 = input[11][2] */
  casadi_copy(arg[11] ? arg[11]+32 : 0, 16, w26);
  /* #45: {NULL, NULL, NULL, NULL, NULL, NULL, @27, @31, NULL, NULL, NULL, NULL} = vertsplit(@26) */
  w27 = w26[10];
  w31 = w26[11];
  /* #46: @32 = @27[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w32, ss=(&w27); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #47: @26 = input[11][3] */
  casadi_copy(arg[11] ? arg[11]+48 : 0, 16, w26);
  /* #48: {NULL, NULL, NULL, NULL, NULL, NULL, @27, @33, NULL, NULL, NULL, NULL} = vertsplit(@26) */
  w27 = w26[10];
  w33 = w26[11];
  /* #49: @34 = @27[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w34, ss=(&w27); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #50: @35 = horzcat(@17, @30, @32, @34) */
  rr=w35;
  for (i=0, cs=w17; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<6; ++i) *rr++ = *cs++;
  /* #51: @36 = fwd4_x(@5, @10, @16, @2, @35) */
  arg1[0]=(&w5);
  arg1[1]=w10;
  arg1[2]=0;
  arg1[3]=w2;
  arg1[4]=w35;
  res1[0]=w36;
  if (casadi_f13(arg1, res1, iw, w, 0)) return 1;
  /* #52: {@27, @37, @38, @39} = horzsplit(@36) */
  w27 = w36[0];
  w37 = w36[1];
  w38 = w36[2];
  w39 = w36[3];
  /* #53: @11 = (@11-@27) */
  w11 -= w27;
  /* #54: @11 = (@6*@11) */
  w11  = (w6*w11);
  /* #55: @27 = input[0][1] */
  w27 = arg[0] ? arg[0][1] : 0;
  /* #56: @40 = input[3][7] */
  w40 = arg[3] ? arg[3][11] : 0;
  /* #57: @10 = @40[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w10, ss=(&w40); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #58: @40 = y(@5, @10) */
  arg1[0]=(&w5);
  arg1[1]=w10;
  res1[0]=(&w40);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #59: @27 = (@27-@40) */
  w27 -= w40;
  /* #60: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #61: @16 = 00 */
  /* #62: @36 = horzcat(@14, @15, @21, @25) */
  rr=w36;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w21;
  *rr++ = w25;
  /* #63: @17 = @28[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w17, ss=(&w28); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #64: @30 = @29[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w30, ss=(&w29); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #65: @32 = @31[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w32, ss=(&w31); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #66: @34 = @33[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w34, ss=(&w33); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #67: @35 = horzcat(@17, @30, @32, @34) */
  rr=w35;
  for (i=0, cs=w17; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<6; ++i) *rr++ = *cs++;
  /* #68: @2 = fwd4_y(@5, @10, @16, @36, @35) */
  arg1[0]=(&w5);
  arg1[1]=w10;
  arg1[2]=0;
  arg1[3]=w36;
  arg1[4]=w35;
  res1[0]=w2;
  if (casadi_f14(arg1, res1, iw, w, 0)) return 1;
  /* #69: {@5, @33, @31, @29} = horzsplit(@2) */
  w5 = w2[0];
  w33 = w2[1];
  w31 = w2[2];
  w29 = w2[3];
  /* #70: @12 = (@12-@5) */
  w12 -= w5;
  /* #71: @12 = (@27*@12) */
  w12  = (w27*w12);
  /* #72: @11 = (@11+@12) */
  w11 += w12;
  /* #73: output[0][5] = @11 */
  if (res[0]) res[0][5] = w11;
  /* #74: @2 = input[9][1] */
  casadi_copy(arg[9] ? arg[9]+4 : 0, 4, w2);
  /* #75: {@11, @12, @5, @28} = vertsplit(@2) */
  w11 = w2[0];
  w12 = w2[1];
  w5 = w2[2];
  w28 = w2[3];
  /* #76: @14 = (@1*@11) */
  w14  = (w1*w11);
  /* #77: @15 = (@9*@13) */
  w15  = (w9*w13);
  /* #78: @15 = (@8*@15) */
  w15  = (w8*w15);
  /* #79: @14 = (@14-@15) */
  w14 -= w15;
  /* #80: output[0][6] = @14 */
  if (res[0]) res[0][6] = w14;
  /* #81: @11 = (@7*@11) */
  w11  = (w7*w11);
  /* #82: @13 = (@0*@13) */
  w13  = (w0*w13);
  /* #83: @13 = (@8*@13) */
  w13  = (w8*w13);
  /* #84: @11 = (@11+@13) */
  w11 += w13;
  /* #85: output[0][7] = @11 */
  if (res[0]) res[0][7] = w11;
  /* #86: output[0][8] = @12 */
  if (res[0]) res[0][8] = w12;
  /* #87: output[0][9] = @5 */
  if (res[0]) res[0][9] = w5;
  /* #88: output[0][10] = @28 */
  if (res[0]) res[0][10] = w28;
  /* #89: @4 = (@4-@37) */
  w4 -= w37;
  /* #90: @4 = (@6*@4) */
  w4  = (w6*w4);
  /* #91: @3 = (@3-@33) */
  w3 -= w33;
  /* #92: @3 = (@27*@3) */
  w3  = (w27*w3);
  /* #93: @4 = (@4+@3) */
  w4 += w3;
  /* #94: output[0][11] = @4 */
  if (res[0]) res[0][11] = w4;
  /* #95: @2 = input[9][2] */
  casadi_copy(arg[9] ? arg[9]+8 : 0, 4, w2);
  /* #96: {@4, @3, @33, @37} = vertsplit(@2) */
  w4 = w2[0];
  w3 = w2[1];
  w33 = w2[2];
  w37 = w2[3];
  /* #97: @28 = (@1*@4) */
  w28  = (w1*w4);
  /* #98: @5 = (@9*@20) */
  w5  = (w9*w20);
  /* #99: @5 = (@8*@5) */
  w5  = (w8*w5);
  /* #100: @28 = (@28-@5) */
  w28 -= w5;
  /* #101: output[0][12] = @28 */
  if (res[0]) res[0][12] = w28;
  /* #102: @4 = (@7*@4) */
  w4  = (w7*w4);
  /* #103: @20 = (@0*@20) */
  w20  = (w0*w20);
  /* #104: @20 = (@8*@20) */
  w20  = (w8*w20);
  /* #105: @4 = (@4+@20) */
  w4 += w20;
  /* #106: output[0][13] = @4 */
  if (res[0]) res[0][13] = w4;
  /* #107: output[0][14] = @3 */
  if (res[0]) res[0][14] = w3;
  /* #108: output[0][15] = @33 */
  if (res[0]) res[0][15] = w33;
  /* #109: output[0][16] = @37 */
  if (res[0]) res[0][16] = w37;
  /* #110: @18 = (@18-@38) */
  w18 -= w38;
  /* #111: @18 = (@6*@18) */
  w18  = (w6*w18);
  /* #112: @19 = (@19-@31) */
  w19 -= w31;
  /* #113: @19 = (@27*@19) */
  w19  = (w27*w19);
  /* #114: @18 = (@18+@19) */
  w18 += w19;
  /* #115: output[0][17] = @18 */
  if (res[0]) res[0][17] = w18;
  /* #116: @2 = input[9][3] */
  casadi_copy(arg[9] ? arg[9]+12 : 0, 4, w2);
  /* #117: {@18, @19, @31, @38} = vertsplit(@2) */
  w18 = w2[0];
  w19 = w2[1];
  w31 = w2[2];
  w38 = w2[3];
  /* #118: @1 = (@1*@18) */
  w1 *= w18;
  /* #119: @9 = (@9*@24) */
  w9 *= w24;
  /* #120: @9 = (@8*@9) */
  w9  = (w8*w9);
  /* #121: @1 = (@1-@9) */
  w1 -= w9;
  /* #122: output[0][18] = @1 */
  if (res[0]) res[0][18] = w1;
  /* #123: @7 = (@7*@18) */
  w7 *= w18;
  /* #124: @0 = (@0*@24) */
  w0 *= w24;
  /* #125: @8 = (@8*@0) */
  w8 *= w0;
  /* #126: @7 = (@7+@8) */
  w7 += w8;
  /* #127: output[0][19] = @7 */
  if (res[0]) res[0][19] = w7;
  /* #128: output[0][20] = @19 */
  if (res[0]) res[0][20] = w19;
  /* #129: output[0][21] = @31 */
  if (res[0]) res[0][21] = w31;
  /* #130: output[0][22] = @38 */
  if (res[0]) res[0][22] = w38;
  /* #131: @22 = (@22-@39) */
  w22 -= w39;
  /* #132: @6 = (@6*@22) */
  w6 *= w22;
  /* #133: @23 = (@23-@29) */
  w23 -= w29;
  /* #134: @27 = (@27*@23) */
  w27 *= w23;
  /* #135: @6 = (@6+@27) */
  w6 += w27;
  /* #136: output[0][23] = @6 */
  if (res[0]) res[0][23] = w6;
  return 0;
}

/* rockit_model_expl_vde_forw:(i0[6],i1[6x6],i2[6x4],i3[4],i4[12])->(o0[6],o1[6x6],o2[6x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+3, *rr, *ss;
  const casadi_real **arg1=arg+5, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, *w6=w+281, *w7=w+287, *w9=w+291, w10, *w11=w+297, *w12=w+301, *w14=w+317, *w18=w+323, *w19=w+359, *w21=w+383, *w23=w+479, *w24=w+515, *w25=w+531, *w26=w+537, *w27=w+542, *w28=w+566, *w29=w+630;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = input[0][4] */
  w4 = arg[0] ? arg[0][4] : 0;
  /* #5: @5 = input[0][5] */
  w5 = arg[0] ? arg[0][5] : 0;
  /* #6: @6 = vertcat(@0, @1, @2, @3, @4, @5) */
  rr=w6;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #7: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #8: @1 = input[3][1] */
  w1 = arg[3] ? arg[3][1] : 0;
  /* #9: @2 = input[3][2] */
  w2 = arg[3] ? arg[3][2] : 0;
  /* #10: @3 = input[3][3] */
  w3 = arg[3] ? arg[3][3] : 0;
  /* #11: @7 = vertcat(@0, @1, @2, @3) */
  rr=w7;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  /* #12: @8 = 0x1 */
  /* #13: @9 = input[4][0] */
  casadi_copy(arg[4], 5, w9);
  /* #14: @0 = input[4][1] */
  w0 = arg[4] ? arg[4][5] : 0;
  /* #15: @1 = input[4][2] */
  w1 = arg[4] ? arg[4][6] : 0;
  /* #16: @2 = input[4][3] */
  w2 = arg[4] ? arg[4][7] : 0;
  /* #17: @3 = input[4][4] */
  w3 = arg[4] ? arg[4][8] : 0;
  /* #18: @4 = input[4][5] */
  w4 = arg[4] ? arg[4][9] : 0;
  /* #19: @5 = input[4][6] */
  w5 = arg[4] ? arg[4][10] : 0;
  /* #20: @10 = input[4][7] */
  w10 = arg[4] ? arg[4][11] : 0;
  /* #21: @11 = [nan, nan, nan, nan] */
  casadi_copy(casadi_c5, 4, w11);
  /* #22: @12 = vertcat(@9, @0, @1, @2, @3, @4, @5, @10, @11) */
  rr=w12;
  for (i=0, cs=w9; i<5; ++i) *rr++ = *cs++;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w10;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #23: @13 = 00 */
  /* #24: {@14, @15, @16} = ode(@6, @7, @8, @12, @13) */
  arg1[0]=w6;
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=w12;
  arg1[4]=0;
  res1[0]=w14;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #25: output[0][0] = @14 */
  casadi_copy(w14, 6, res[0]);
  /* #26: @17 = zeros(6x1,0nz) */
  /* #27: @18 = input[1][0] */
  casadi_copy(arg[1], 36, w18);
  /* #28: @19 = zeros(4x6) */
  casadi_clear(w19, 24);
  /* #29: @20 = 0x6 */
  /* #30: @21 = zeros(16x6) */
  casadi_clear(w21, 96);
  /* #31: @22 = zeros(1x6,0nz) */
  /* #32: {@23, NULL, NULL} = fwd6_ode(@6, @7, @8, @12, @13, @17, @15, @16, @18, @19, @20, @21, @22) */
  arg1[0]=w6;
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=w12;
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=0;
  arg1[7]=0;
  arg1[8]=w18;
  arg1[9]=w19;
  arg1[10]=0;
  arg1[11]=w21;
  arg1[12]=0;
  res1[0]=w23;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #33: output[1][0] = @23 */
  casadi_copy(w23, 36, res[1]);
  /* #34: @9 = zeros(4x6,5nz) */
  casadi_clear(w9, 5);
  /* #35: @17 = zeros(6x1,0nz) */
  /* #36: @14 = zeros(6x1) */
  casadi_clear(w14, 6);
  /* #37: @11 = ones(4x1) */
  casadi_fill(w11, 4, 1.);
  /* #38: @20 = 0x1 */
  /* #39: @24 = zeros(16x1) */
  casadi_clear(w24, 16);
  /* #40: @22 = 00 */
  /* #41: {@25, NULL, NULL} = fwd1_ode(@6, @7, @8, @12, @13, @17, @15, @16, @14, @11, @20, @24, @22) */
  arg1[0]=w6;
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=w12;
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=0;
  arg1[7]=0;
  arg1[8]=w14;
  arg1[9]=w11;
  arg1[10]=0;
  arg1[11]=w24;
  arg1[12]=0;
  res1[0]=w25;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #42: @26 = @25[:5] */
  for (rr=w26, ss=w25+0; ss!=w25+5; ss+=1) *rr++ = *ss;
  /* #43: (@9[:5] = @26) */
  for (rr=w9+0, ss=w26; rr!=w9+5; rr+=1) *rr = *ss++;
  /* #44: @26 = @9' */
  casadi_trans(w9,casadi_s12, w26, casadi_s11, iw);
  /* #45: @19 = dense(@26) */
  casadi_densify(w26, casadi_s11, w19, 0);
  /* #46: @17 = zeros(6x1,0nz) */
  /* #47: @27 = input[2][0] */
  casadi_copy(arg[2], 24, w27);
  /* #48: @24 = zeros(4x4) */
  casadi_clear(w24, 16);
  /* #49: @20 = 0x4 */
  /* #50: @28 = zeros(16x4) */
  casadi_clear(w28, 64);
  /* #51: @22 = zeros(1x4,0nz) */
  /* #52: {@29, NULL, NULL} = fwd4_ode(@6, @7, @8, @12, @13, @17, @15, @16, @27, @24, @20, @28, @22) */
  arg1[0]=w6;
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=w12;
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=0;
  arg1[7]=0;
  arg1[8]=w27;
  arg1[9]=w24;
  arg1[10]=0;
  arg1[11]=w28;
  arg1[12]=0;
  res1[0]=w29;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f12(arg1, res1, iw, w, 0)) return 1;
  /* #53: @19 = (@19+@29) */
  for (i=0, rr=w19, cs=w29; i<24; ++i) (*rr++) += (*cs++);
  /* #54: output[2][0] = @19 */
  casadi_copy(w19, 24, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rockit_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void rockit_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real rockit_model_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s13;
    case 1: return casadi_s14;
    case 2: return casadi_s15;
    case 3: return casadi_s16;
    case 4: return casadi_s17;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s13;
    case 1: return casadi_s14;
    case 2: return casadi_s15;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 41;
  if (sz_res) *sz_res = 26;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 654;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
