/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rockit_model_constr_h_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_flip CASADI_PREFIX(flip)
#define casadi_interpn CASADI_PREFIX(interpn)
#define casadi_interpn_interpolate CASADI_PREFIX(interpn_interpolate)
#define casadi_interpn_weights CASADI_PREFIX(interpn_weights)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_interpn_weights(casadi_int ndim, const casadi_real* grid, const casadi_int* offset, const casadi_real* x, casadi_real* alpha, casadi_int* index, const casadi_int* lookup_mode) {
  casadi_int i;
  for (i=0; i<ndim; ++i) {
    casadi_int ng, j;
    casadi_real xi;
    const casadi_real* g;
    xi = x ? x[i] : 0;
    g = grid + offset[i];
    ng = offset[i+1]-offset[i];
    j = index[i] = casadi_low(xi, g, ng, lookup_mode[i]);
    alpha[i] = (xi-g[j])/(g[j+1]-g[j]);
  }
}

void casadi_interpn_interpolate(casadi_real* res, casadi_int ndim, const casadi_int* offset, const casadi_real* values, const casadi_real* alpha, const casadi_int* index, const casadi_int* corner, casadi_real* coeff, casadi_int m) {
  casadi_real c;
  casadi_int ld, i;
  c=1;
  ld=1;
  for (i=0; i<ndim; ++i) {
    if (coeff) *coeff++ = c;
    if (corner[i]) {
      c *= alpha[i];
    } else {
      c *= 1-alpha[i];
    }
    values += (index[i]+corner[i])*ld*m;
    ld *= offset[i+1]-offset[i];
  }
  if (coeff) {
    for (i=0;i<m;++i) res[i] += values[i];
  } else {
    for (i=0;i<m;++i) res[i] += c*values[i];
  }
}

casadi_int casadi_flip(casadi_int* corner, casadi_int ndim) {
  casadi_int i;
  for (i=0; i<ndim; ++i) {
    if (corner[i]) {
      corner[i]=0;
    } else {
      corner[i]=1;
      return 1;
    }
  }
  return 0;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_interpn(casadi_real* res, casadi_int ndim, const casadi_real* grid, const casadi_int* offset, const casadi_real* values, const casadi_real* x, const casadi_int* lookup_mode, casadi_int m, casadi_int* iw, casadi_real* w) {
  casadi_real* alpha;
  casadi_int *index, *corner;
  alpha = w; w += ndim;
  index = iw; iw += ndim;
  corner = iw; iw += ndim;
  casadi_interpn_weights(ndim, grid, offset, x, alpha, index, lookup_mode);
  casadi_clear_casadi_int(corner, ndim);
  casadi_clear(res, m);
  do {
    casadi_real* coeff = 0;
    casadi_interpn_interpolate(res, ndim, offset, values,
      alpha, index, corner, coeff, m);
  } while (casadi_flip(corner, ndim));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[1] = {0};
static const casadi_int casadi_s1[2] = {0, 6};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {3};
static const casadi_int casadi_s4[2] = {0, 22};
static const casadi_int casadi_s5[6] = {0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s6[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[3] = {0, 0, 0};
static const casadi_int casadi_s8[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s9[5] = {1, 1, 0, 1, 0};

static const casadi_real casadi_c0[6] = {0., 2.0000000000000001e-01, 4.0000000000000002e-01, 6.0000000000000009e-01, 8.0000000000000004e-01, 1.};
static const casadi_real casadi_c1[18] = {0., 3.2666666666666656e-02, 6.6666666666666666e-02, 1.3333333333333333e-01, 2.0000000000000004e-01, 2.6666666666666666e-01, 3.3333333333333331e-01, 4.0000000000000008e-01, 4.6666666666666673e-01, 5.3333333333333333e-01, 6.0000000000000009e-01, 6.6666666666666663e-01, 7.3333333333333339e-01, 8.0000000000000016e-01, 8.6666666666666670e-01, 9.3333333333333324e-01, 9.6733333333333338e-01, 1.};
static const casadi_real casadi_c2[22] = {0., 0., 0., 0., 9.7999999999999976e-02, 1.0200000000000004e-01, 2.0000000000000001e-01, 2.9799999999999999e-01, 3.0200000000000005e-01, 4.0000000000000002e-01, 4.9800000000000000e-01, 5.0200000000000011e-01, 6.0000000000000009e-01, 6.9800000000000006e-01, 7.0200000000000007e-01, 8.0000000000000004e-01, 8.9800000000000002e-01, 9.0200000000000002e-01, 1., 1., 1., 1.};

/* linear:(x,c[6])->(f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    if (res[0]) {
        casadi_interpn(res[0], 1, casadi_c0, casadi_s1, arg[1], arg[0], casadi_s0, 1, iw, w);
      }
  return 0;
}

/* x:(x,c[6])->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+2;
  casadi_real w0, *w1=w+10, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+46, w21;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w1);
  /* #2: {@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19} = horzsplit(@1) */
  w2 = w1[0];
  w3 = w1[1];
  w4 = w1[2];
  w5 = w1[3];
  w6 = w1[4];
  w7 = w1[5];
  w8 = w1[6];
  w9 = w1[7];
  w10 = w1[8];
  w11 = w1[9];
  w12 = w1[10];
  w13 = w1[11];
  w14 = w1[12];
  w15 = w1[13];
  w16 = w1[14];
  w17 = w1[15];
  w18 = w1[16];
  w19 = w1[17];
  /* #3: @20 = input[1][0] */
  casadi_copy(arg[1], 6, w20);
  /* #4: @21 = linear(@2, @20) */
  arg1[0]=(&w2);
  arg1[1]=w20;
  res1[0]=(&w21);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #5: @2 = linear(@3, @20) */
  arg1[0]=(&w3);
  arg1[1]=w20;
  res1[0]=(&w2);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @20) */
  arg1[0]=(&w4);
  arg1[1]=w20;
  res1[0]=(&w3);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @20) */
  arg1[0]=(&w5);
  arg1[1]=w20;
  res1[0]=(&w4);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @20) */
  arg1[0]=(&w6);
  arg1[1]=w20;
  res1[0]=(&w5);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @20) */
  arg1[0]=(&w7);
  arg1[1]=w20;
  res1[0]=(&w6);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @20) */
  arg1[0]=(&w8);
  arg1[1]=w20;
  res1[0]=(&w7);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @20) */
  arg1[0]=(&w9);
  arg1[1]=w20;
  res1[0]=(&w8);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @20) */
  arg1[0]=(&w10);
  arg1[1]=w20;
  res1[0]=(&w9);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @20) */
  arg1[0]=(&w11);
  arg1[1]=w20;
  res1[0]=(&w10);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @20) */
  arg1[0]=(&w12);
  arg1[1]=w20;
  res1[0]=(&w11);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @20) */
  arg1[0]=(&w13);
  arg1[1]=w20;
  res1[0]=(&w12);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @20) */
  arg1[0]=(&w14);
  arg1[1]=w20;
  res1[0]=(&w13);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @20) */
  arg1[0]=(&w15);
  arg1[1]=w20;
  res1[0]=(&w14);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @20) */
  arg1[0]=(&w16);
  arg1[1]=w20;
  res1[0]=(&w15);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @20) */
  arg1[0]=(&w17);
  arg1[1]=w20;
  res1[0]=(&w16);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @20) */
  arg1[0]=(&w18);
  arg1[1]=w20;
  res1[0]=(&w17);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @20) */
  arg1[0]=(&w19);
  arg1[1]=w20;
  res1[0]=(&w18);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #22: @1 = horzcat(@21, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w1;
  *rr++ = w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #23: @21 = BSplineParametric(@0) */
  casadi_clear((&w21), 1);
  CASADI_PREFIX(nd_boor_eval)((&w21),1,casadi_c2,casadi_s4,casadi_s3,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #24: output[0][0] = @21 */
  if (res[0]) res[0][0] = w21;
  return 0;
}

/* linear:(x,c[6])->(f) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    if (res[0]) {
        casadi_interpn(res[0], 1, casadi_c0, casadi_s1, arg[1], arg[0], casadi_s0, 1, iw, w);
      }
  return 0;
}

/* y:(x,c[6])->(f) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+2;
  casadi_real w0, *w1=w+10, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+46, w21;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w1);
  /* #2: {@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19} = horzsplit(@1) */
  w2 = w1[0];
  w3 = w1[1];
  w4 = w1[2];
  w5 = w1[3];
  w6 = w1[4];
  w7 = w1[5];
  w8 = w1[6];
  w9 = w1[7];
  w10 = w1[8];
  w11 = w1[9];
  w12 = w1[10];
  w13 = w1[11];
  w14 = w1[12];
  w15 = w1[13];
  w16 = w1[14];
  w17 = w1[15];
  w18 = w1[16];
  w19 = w1[17];
  /* #3: @20 = input[1][0] */
  casadi_copy(arg[1], 6, w20);
  /* #4: @21 = linear(@2, @20) */
  arg1[0]=(&w2);
  arg1[1]=w20;
  res1[0]=(&w21);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #5: @2 = linear(@3, @20) */
  arg1[0]=(&w3);
  arg1[1]=w20;
  res1[0]=(&w2);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @20) */
  arg1[0]=(&w4);
  arg1[1]=w20;
  res1[0]=(&w3);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @20) */
  arg1[0]=(&w5);
  arg1[1]=w20;
  res1[0]=(&w4);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @20) */
  arg1[0]=(&w6);
  arg1[1]=w20;
  res1[0]=(&w5);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @20) */
  arg1[0]=(&w7);
  arg1[1]=w20;
  res1[0]=(&w6);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @20) */
  arg1[0]=(&w8);
  arg1[1]=w20;
  res1[0]=(&w7);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @20) */
  arg1[0]=(&w9);
  arg1[1]=w20;
  res1[0]=(&w8);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @20) */
  arg1[0]=(&w10);
  arg1[1]=w20;
  res1[0]=(&w9);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @20) */
  arg1[0]=(&w11);
  arg1[1]=w20;
  res1[0]=(&w10);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @20) */
  arg1[0]=(&w12);
  arg1[1]=w20;
  res1[0]=(&w11);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @20) */
  arg1[0]=(&w13);
  arg1[1]=w20;
  res1[0]=(&w12);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @20) */
  arg1[0]=(&w14);
  arg1[1]=w20;
  res1[0]=(&w13);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @20) */
  arg1[0]=(&w15);
  arg1[1]=w20;
  res1[0]=(&w14);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @20) */
  arg1[0]=(&w16);
  arg1[1]=w20;
  res1[0]=(&w15);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @20) */
  arg1[0]=(&w17);
  arg1[1]=w20;
  res1[0]=(&w16);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @20) */
  arg1[0]=(&w18);
  arg1[1]=w20;
  res1[0]=(&w17);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @20) */
  arg1[0]=(&w19);
  arg1[1]=w20;
  res1[0]=(&w18);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #22: @1 = horzcat(@21, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w1;
  *rr++ = w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #23: @21 = BSplineParametric(@0) */
  casadi_clear((&w21), 1);
  CASADI_PREFIX(nd_boor_eval)((&w21),1,casadi_c2,casadi_s4,casadi_s3,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #24: output[0][0] = @21 */
  if (res[0]) res[0][0] = w21;
  return 0;
}

/* linear:(x,c[6])->(f) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    if (res[0]) {
        casadi_interpn(res[0], 1, casadi_c0, casadi_s1, arg[1], arg[0], casadi_s0, 1, iw, w);
      }
  return 0;
}

/* r:(x,c[6])->(f) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+2;
  casadi_real w0, *w1=w+10, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+46, w21;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w1);
  /* #2: {@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19} = horzsplit(@1) */
  w2 = w1[0];
  w3 = w1[1];
  w4 = w1[2];
  w5 = w1[3];
  w6 = w1[4];
  w7 = w1[5];
  w8 = w1[6];
  w9 = w1[7];
  w10 = w1[8];
  w11 = w1[9];
  w12 = w1[10];
  w13 = w1[11];
  w14 = w1[12];
  w15 = w1[13];
  w16 = w1[14];
  w17 = w1[15];
  w18 = w1[16];
  w19 = w1[17];
  /* #3: @20 = input[1][0] */
  casadi_copy(arg[1], 6, w20);
  /* #4: @21 = linear(@2, @20) */
  arg1[0]=(&w2);
  arg1[1]=w20;
  res1[0]=(&w21);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #5: @2 = linear(@3, @20) */
  arg1[0]=(&w3);
  arg1[1]=w20;
  res1[0]=(&w2);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @20) */
  arg1[0]=(&w4);
  arg1[1]=w20;
  res1[0]=(&w3);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @20) */
  arg1[0]=(&w5);
  arg1[1]=w20;
  res1[0]=(&w4);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @20) */
  arg1[0]=(&w6);
  arg1[1]=w20;
  res1[0]=(&w5);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @20) */
  arg1[0]=(&w7);
  arg1[1]=w20;
  res1[0]=(&w6);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @20) */
  arg1[0]=(&w8);
  arg1[1]=w20;
  res1[0]=(&w7);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @20) */
  arg1[0]=(&w9);
  arg1[1]=w20;
  res1[0]=(&w8);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @20) */
  arg1[0]=(&w10);
  arg1[1]=w20;
  res1[0]=(&w9);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @20) */
  arg1[0]=(&w11);
  arg1[1]=w20;
  res1[0]=(&w10);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @20) */
  arg1[0]=(&w12);
  arg1[1]=w20;
  res1[0]=(&w11);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @20) */
  arg1[0]=(&w13);
  arg1[1]=w20;
  res1[0]=(&w12);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @20) */
  arg1[0]=(&w14);
  arg1[1]=w20;
  res1[0]=(&w13);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @20) */
  arg1[0]=(&w15);
  arg1[1]=w20;
  res1[0]=(&w14);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @20) */
  arg1[0]=(&w16);
  arg1[1]=w20;
  res1[0]=(&w15);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @20) */
  arg1[0]=(&w17);
  arg1[1]=w20;
  res1[0]=(&w16);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @20) */
  arg1[0]=(&w18);
  arg1[1]=w20;
  res1[0]=(&w17);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @20) */
  arg1[0]=(&w19);
  arg1[1]=w20;
  res1[0]=(&w18);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #22: @1 = horzcat(@21, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w1;
  *rr++ = w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #23: @21 = BSplineParametric(@0) */
  casadi_clear((&w21), 1);
  CASADI_PREFIX(nd_boor_eval)((&w21),1,casadi_c2,casadi_s4,casadi_s3,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #24: output[0][0] = @21 */
  if (res[0]) res[0][0] = w21;
  return 0;
}

/* rockit_model_constr_h_e_fun:(i0[6],i1[],i2[],i3[12])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_int *cii;
  const casadi_real **arg1=arg+4;
  casadi_real w0, w1, w2, *w3=w+57, w4;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #2: @2 = input[3][3] */
  w2 = arg[3] ? arg[3][7] : 0;
  /* #3: @3 = @2[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w3, ss=(&w2); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #4: @2 = x(@1, @3) */
  arg1[0]=(&w1);
  arg1[1]=w3;
  res1[0]=(&w2);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #5: @0 = (@0-@2) */
  w0 -= w2;
  /* #6: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #7: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #8: @4 = input[3][4] */
  w4 = arg[3] ? arg[3][8] : 0;
  /* #9: @3 = @4[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w3, ss=(&w4); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #10: @4 = y(@1, @3) */
  arg1[0]=(&w1);
  arg1[1]=w3;
  res1[0]=(&w4);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #11: @2 = (@2-@4) */
  w2 -= w4;
  /* #12: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #13: @0 = (@0+@2) */
  w0 += w2;
  /* #14: @2 = input[3][5] */
  w2 = arg[3] ? arg[3][9] : 0;
  /* #15: @3 = @2[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s5, rr=w3, ss=(&w2); cii!=casadi_s5+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #16: @2 = r(@1, @3) */
  arg1[0]=(&w1);
  arg1[1]=w3;
  res1[0]=(&w2);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #17: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #18: @0 = (@0-@2) */
  w0 -= w2;
  /* #19: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_constr_h_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rockit_model_constr_h_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_constr_h_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_constr_h_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rockit_model_constr_h_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_constr_h_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rockit_model_constr_h_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void rockit_model_constr_h_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_constr_h_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_constr_h_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rockit_model_constr_h_e_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_constr_h_e_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_constr_h_e_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_constr_h_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_constr_h_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rockit_model_constr_h_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 26;
  if (sz_res) *sz_res = 21;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 64;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
