/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rockit_model_constr_h_fun_jac_uxt_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f15 CASADI_PREFIX(f15)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_flip CASADI_PREFIX(flip)
#define casadi_interpn CASADI_PREFIX(interpn)
#define casadi_interpn_interpolate CASADI_PREFIX(interpn_interpolate)
#define casadi_interpn_weights CASADI_PREFIX(interpn_weights)
#define casadi_low CASADI_PREFIX(low)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_interpn_weights(casadi_int ndim, const casadi_real* grid, const casadi_int* offset, const casadi_real* x, casadi_real* alpha, casadi_int* index, const casadi_int* lookup_mode) {
  casadi_int i;
  for (i=0; i<ndim; ++i) {
    casadi_int ng, j;
    casadi_real xi;
    const casadi_real* g;
    xi = x ? x[i] : 0;
    g = grid + offset[i];
    ng = offset[i+1]-offset[i];
    j = index[i] = casadi_low(xi, g, ng, lookup_mode[i]);
    alpha[i] = (xi-g[j])/(g[j+1]-g[j]);
  }
}

void casadi_interpn_interpolate(casadi_real* res, casadi_int ndim, const casadi_int* offset, const casadi_real* values, const casadi_real* alpha, const casadi_int* index, const casadi_int* corner, casadi_real* coeff, casadi_int m) {
  casadi_real c;
  casadi_int ld, i;
  c=1;
  ld=1;
  for (i=0; i<ndim; ++i) {
    if (coeff) *coeff++ = c;
    if (corner[i]) {
      c *= alpha[i];
    } else {
      c *= 1-alpha[i];
    }
    values += (index[i]+corner[i])*ld*m;
    ld *= offset[i+1]-offset[i];
  }
  if (coeff) {
    for (i=0;i<m;++i) res[i] += values[i];
  } else {
    for (i=0;i<m;++i) res[i] += c*values[i];
  }
}

casadi_int casadi_flip(casadi_int* corner, casadi_int ndim) {
  casadi_int i;
  for (i=0; i<ndim; ++i) {
    if (corner[i]) {
      corner[i]=0;
    } else {
      corner[i]=1;
      return 1;
    }
  }
  return 0;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_interpn(casadi_real* res, casadi_int ndim, const casadi_real* grid, const casadi_int* offset, const casadi_real* values, const casadi_real* x, const casadi_int* lookup_mode, casadi_int m, casadi_int* iw, casadi_real* w) {
  casadi_real* alpha;
  casadi_int *index, *corner;
  alpha = w; w += ndim;
  index = iw; iw += ndim;
  corner = iw; iw += ndim;
  casadi_interpn_weights(ndim, grid, offset, x, alpha, index, lookup_mode);
  casadi_clear_casadi_int(corner, ndim);
  casadi_clear(res, m);
  do {
    casadi_real* coeff = 0;
    casadi_interpn_interpolate(res, ndim, offset, values,
      alpha, index, corner, coeff, m);
  } while (casadi_flip(corner, ndim));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[1] = {0};
static const casadi_int casadi_s1[2] = {0, 6};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {3};
static const casadi_int casadi_s4[2] = {0, 22};
static const casadi_int casadi_s5[37] = {1, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s6[54] = {18, 17, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17};
static const casadi_int casadi_s7[39] = {1, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s8[1] = {2};
static const casadi_int casadi_s9[2] = {0, 20};
static const casadi_int casadi_s10[35] = {1, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s11[51] = {17, 16, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16};
static const casadi_int casadi_s12[2] = {0, 18};
static const casadi_int casadi_s13[6] = {0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s14[6] = {1, 2, 0, 0, 1, 0};
static const casadi_int casadi_s15[3] = {1, 3, 6};
static const casadi_int casadi_s16[20] = {10, 10, 0, 0, 0, 0, 0, 2, 4, 4, 4, 7, 7, 4, 8, 5, 8, 4, 5, 8};
static const casadi_int casadi_s17[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s18[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s19[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s20[3] = {0, 0, 0};
static const casadi_int casadi_s21[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s22[7] = {10, 1, 0, 3, 4, 5, 8};
static const casadi_int casadi_s23[3] = {1, 0, 0};

static const casadi_real casadi_c0[6] = {0., 2.0000000000000001e-01, 4.0000000000000002e-01, 6.0000000000000009e-01, 8.0000000000000004e-01, 1.};
static const casadi_real casadi_c1[18] = {0., 3.2666666666666656e-02, 6.6666666666666666e-02, 1.3333333333333333e-01, 2.0000000000000004e-01, 2.6666666666666666e-01, 3.3333333333333331e-01, 4.0000000000000008e-01, 4.6666666666666673e-01, 5.3333333333333333e-01, 6.0000000000000009e-01, 6.6666666666666663e-01, 7.3333333333333339e-01, 8.0000000000000016e-01, 8.6666666666666670e-01, 9.3333333333333324e-01, 9.6733333333333338e-01, 1.};
static const casadi_real casadi_c2[22] = {0., 0., 0., 0., 9.7999999999999976e-02, 1.0200000000000004e-01, 2.0000000000000001e-01, 2.9799999999999999e-01, 3.0200000000000005e-01, 4.0000000000000002e-01, 4.9800000000000000e-01, 5.0200000000000011e-01, 6.0000000000000009e-01, 6.9800000000000006e-01, 7.0200000000000007e-01, 8.0000000000000004e-01, 8.9800000000000002e-01, 9.0200000000000002e-01, 1., 1., 1., 1.};
static const casadi_real casadi_c3[34] = {-3.0612244897959194e+01, 3.0612244897959194e+01, -2.9411764705882344e+01, 2.9411764705882344e+01, -15., 15., -15., 15., -15., 15., -15., 15., -15., 15., -1.4999999999999995e+01, 1.4999999999999995e+01, -1.4999999999999995e+01, 1.4999999999999995e+01, -1.4999999999999995e+01, 1.4999999999999995e+01, -1.5000000000000004e+01, 1.5000000000000004e+01, -1.5000000000000004e+01, 1.5000000000000004e+01, -1.5000000000000004e+01, 1.5000000000000004e+01, -1.5000000000000004e+01, 1.5000000000000004e+01, -1.5000000000000004e+01, 1.5000000000000004e+01, -2.9411764705882362e+01, 2.9411764705882362e+01, -3.0612244897959194e+01, 3.0612244897959194e+01};
static const casadi_real casadi_c4[20] = {0., 0., 0., 9.7999999999999976e-02, 1.0200000000000004e-01, 2.0000000000000001e-01, 2.9799999999999999e-01, 3.0200000000000005e-01, 4.0000000000000002e-01, 4.9800000000000000e-01, 5.0200000000000011e-01, 6.0000000000000009e-01, 6.9800000000000006e-01, 7.0200000000000007e-01, 8.0000000000000004e-01, 8.9800000000000002e-01, 9.0200000000000002e-01, 1., 1., 1.};
static const casadi_real casadi_c5[32] = {-2.0408163265306129e+01, 2.0408163265306129e+01, -1.9607843137254896e+01, 1.9607843137254896e+01, -1.9607843137254896e+01, 1.9607843137254896e+01, -1.0204081632653065e+01, 1.0204081632653065e+01, -1.9607843137254896e+01, 1.9607843137254896e+01, -1.9607843137254896e+01, 1.9607843137254896e+01, -1.0204081632653065e+01, 1.0204081632653065e+01, -1.9607843137254886e+01, 1.9607843137254886e+01, -1.9607843137254886e+01, 1.9607843137254886e+01, -1.0204081632653065e+01, 1.0204081632653065e+01, -1.9607843137254907e+01, 1.9607843137254907e+01, -1.9607843137254907e+01, 1.9607843137254907e+01, -1.0204081632653065e+01, 1.0204081632653065e+01, -1.9607843137254907e+01, 1.9607843137254907e+01, -1.9607843137254907e+01, 1.9607843137254907e+01, -2.0408163265306129e+01, 2.0408163265306129e+01};
static const casadi_real casadi_c6[18] = {0., 0., 9.7999999999999976e-02, 1.0200000000000004e-01, 2.0000000000000001e-01, 2.9799999999999999e-01, 3.0200000000000005e-01, 4.0000000000000002e-01, 4.9800000000000000e-01, 5.0200000000000011e-01, 6.0000000000000009e-01, 6.9800000000000006e-01, 7.0200000000000007e-01, 8.0000000000000004e-01, 8.9800000000000002e-01, 9.0200000000000002e-01, 1., 1.};

/* linear:(x,c[6])->(f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    if (res[0]) {
        casadi_interpn(res[0], 1, casadi_c0, casadi_s1, arg[1], arg[0], casadi_s0, 1, iw, w);
      }
  return 0;
}

/* x:(x,c[6])->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+2;
  casadi_real w0, *w1=w+10, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+46, w21;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w1);
  /* #2: {@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19} = horzsplit(@1) */
  w2 = w1[0];
  w3 = w1[1];
  w4 = w1[2];
  w5 = w1[3];
  w6 = w1[4];
  w7 = w1[5];
  w8 = w1[6];
  w9 = w1[7];
  w10 = w1[8];
  w11 = w1[9];
  w12 = w1[10];
  w13 = w1[11];
  w14 = w1[12];
  w15 = w1[13];
  w16 = w1[14];
  w17 = w1[15];
  w18 = w1[16];
  w19 = w1[17];
  /* #3: @20 = input[1][0] */
  casadi_copy(arg[1], 6, w20);
  /* #4: @21 = linear(@2, @20) */
  arg1[0]=(&w2);
  arg1[1]=w20;
  res1[0]=(&w21);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #5: @2 = linear(@3, @20) */
  arg1[0]=(&w3);
  arg1[1]=w20;
  res1[0]=(&w2);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @20) */
  arg1[0]=(&w4);
  arg1[1]=w20;
  res1[0]=(&w3);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @20) */
  arg1[0]=(&w5);
  arg1[1]=w20;
  res1[0]=(&w4);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @20) */
  arg1[0]=(&w6);
  arg1[1]=w20;
  res1[0]=(&w5);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @20) */
  arg1[0]=(&w7);
  arg1[1]=w20;
  res1[0]=(&w6);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @20) */
  arg1[0]=(&w8);
  arg1[1]=w20;
  res1[0]=(&w7);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @20) */
  arg1[0]=(&w9);
  arg1[1]=w20;
  res1[0]=(&w8);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @20) */
  arg1[0]=(&w10);
  arg1[1]=w20;
  res1[0]=(&w9);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @20) */
  arg1[0]=(&w11);
  arg1[1]=w20;
  res1[0]=(&w10);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @20) */
  arg1[0]=(&w12);
  arg1[1]=w20;
  res1[0]=(&w11);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @20) */
  arg1[0]=(&w13);
  arg1[1]=w20;
  res1[0]=(&w12);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @20) */
  arg1[0]=(&w14);
  arg1[1]=w20;
  res1[0]=(&w13);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @20) */
  arg1[0]=(&w15);
  arg1[1]=w20;
  res1[0]=(&w14);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @20) */
  arg1[0]=(&w16);
  arg1[1]=w20;
  res1[0]=(&w15);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @20) */
  arg1[0]=(&w17);
  arg1[1]=w20;
  res1[0]=(&w16);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @20) */
  arg1[0]=(&w18);
  arg1[1]=w20;
  res1[0]=(&w17);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @20) */
  arg1[0]=(&w19);
  arg1[1]=w20;
  res1[0]=(&w18);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #22: @1 = horzcat(@21, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w1;
  *rr++ = w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #23: @21 = BSplineParametric(@0) */
  casadi_clear((&w21), 1);
  CASADI_PREFIX(nd_boor_eval)((&w21),1,casadi_c2,casadi_s4,casadi_s3,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #24: output[0][0] = @21 */
  if (res[0]) res[0][0] = w21;
  return 0;
}

/* linear:(x,c[6])->(f) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    if (res[0]) {
        casadi_interpn(res[0], 1, casadi_c0, casadi_s1, arg[1], arg[0], casadi_s0, 1, iw, w);
      }
  return 0;
}

/* y:(x,c[6])->(f) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+2;
  casadi_real w0, *w1=w+10, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+46, w21;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w1);
  /* #2: {@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19} = horzsplit(@1) */
  w2 = w1[0];
  w3 = w1[1];
  w4 = w1[2];
  w5 = w1[3];
  w6 = w1[4];
  w7 = w1[5];
  w8 = w1[6];
  w9 = w1[7];
  w10 = w1[8];
  w11 = w1[9];
  w12 = w1[10];
  w13 = w1[11];
  w14 = w1[12];
  w15 = w1[13];
  w16 = w1[14];
  w17 = w1[15];
  w18 = w1[16];
  w19 = w1[17];
  /* #3: @20 = input[1][0] */
  casadi_copy(arg[1], 6, w20);
  /* #4: @21 = linear(@2, @20) */
  arg1[0]=(&w2);
  arg1[1]=w20;
  res1[0]=(&w21);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #5: @2 = linear(@3, @20) */
  arg1[0]=(&w3);
  arg1[1]=w20;
  res1[0]=(&w2);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @20) */
  arg1[0]=(&w4);
  arg1[1]=w20;
  res1[0]=(&w3);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @20) */
  arg1[0]=(&w5);
  arg1[1]=w20;
  res1[0]=(&w4);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @20) */
  arg1[0]=(&w6);
  arg1[1]=w20;
  res1[0]=(&w5);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @20) */
  arg1[0]=(&w7);
  arg1[1]=w20;
  res1[0]=(&w6);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @20) */
  arg1[0]=(&w8);
  arg1[1]=w20;
  res1[0]=(&w7);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @20) */
  arg1[0]=(&w9);
  arg1[1]=w20;
  res1[0]=(&w8);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @20) */
  arg1[0]=(&w10);
  arg1[1]=w20;
  res1[0]=(&w9);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @20) */
  arg1[0]=(&w11);
  arg1[1]=w20;
  res1[0]=(&w10);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @20) */
  arg1[0]=(&w12);
  arg1[1]=w20;
  res1[0]=(&w11);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @20) */
  arg1[0]=(&w13);
  arg1[1]=w20;
  res1[0]=(&w12);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @20) */
  arg1[0]=(&w14);
  arg1[1]=w20;
  res1[0]=(&w13);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @20) */
  arg1[0]=(&w15);
  arg1[1]=w20;
  res1[0]=(&w14);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @20) */
  arg1[0]=(&w16);
  arg1[1]=w20;
  res1[0]=(&w15);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @20) */
  arg1[0]=(&w17);
  arg1[1]=w20;
  res1[0]=(&w16);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @20) */
  arg1[0]=(&w18);
  arg1[1]=w20;
  res1[0]=(&w17);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @20) */
  arg1[0]=(&w19);
  arg1[1]=w20;
  res1[0]=(&w18);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #22: @1 = horzcat(@21, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w1;
  *rr++ = w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #23: @21 = BSplineParametric(@0) */
  casadi_clear((&w21), 1);
  CASADI_PREFIX(nd_boor_eval)((&w21),1,casadi_c2,casadi_s4,casadi_s3,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #24: output[0][0] = @21 */
  if (res[0]) res[0][0] = w21;
  return 0;
}

/* linear:(x,c[6])->(f) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    if (res[0]) {
        casadi_interpn(res[0], 1, casadi_c0, casadi_s1, arg[1], arg[0], casadi_s0, 1, iw, w);
      }
  return 0;
}

/* r:(x,c[6])->(f) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+2;
  casadi_real w0, *w1=w+10, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+46, w21;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w1);
  /* #2: {@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19} = horzsplit(@1) */
  w2 = w1[0];
  w3 = w1[1];
  w4 = w1[2];
  w5 = w1[3];
  w6 = w1[4];
  w7 = w1[5];
  w8 = w1[6];
  w9 = w1[7];
  w10 = w1[8];
  w11 = w1[9];
  w12 = w1[10];
  w13 = w1[11];
  w14 = w1[12];
  w15 = w1[13];
  w16 = w1[14];
  w17 = w1[15];
  w18 = w1[16];
  w19 = w1[17];
  /* #3: @20 = input[1][0] */
  casadi_copy(arg[1], 6, w20);
  /* #4: @21 = linear(@2, @20) */
  arg1[0]=(&w2);
  arg1[1]=w20;
  res1[0]=(&w21);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #5: @2 = linear(@3, @20) */
  arg1[0]=(&w3);
  arg1[1]=w20;
  res1[0]=(&w2);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @20) */
  arg1[0]=(&w4);
  arg1[1]=w20;
  res1[0]=(&w3);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @20) */
  arg1[0]=(&w5);
  arg1[1]=w20;
  res1[0]=(&w4);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @20) */
  arg1[0]=(&w6);
  arg1[1]=w20;
  res1[0]=(&w5);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @20) */
  arg1[0]=(&w7);
  arg1[1]=w20;
  res1[0]=(&w6);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @20) */
  arg1[0]=(&w8);
  arg1[1]=w20;
  res1[0]=(&w7);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @20) */
  arg1[0]=(&w9);
  arg1[1]=w20;
  res1[0]=(&w8);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @20) */
  arg1[0]=(&w10);
  arg1[1]=w20;
  res1[0]=(&w9);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @20) */
  arg1[0]=(&w11);
  arg1[1]=w20;
  res1[0]=(&w10);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @20) */
  arg1[0]=(&w12);
  arg1[1]=w20;
  res1[0]=(&w11);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @20) */
  arg1[0]=(&w13);
  arg1[1]=w20;
  res1[0]=(&w12);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @20) */
  arg1[0]=(&w14);
  arg1[1]=w20;
  res1[0]=(&w13);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @20) */
  arg1[0]=(&w15);
  arg1[1]=w20;
  res1[0]=(&w14);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @20) */
  arg1[0]=(&w16);
  arg1[1]=w20;
  res1[0]=(&w15);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @20) */
  arg1[0]=(&w17);
  arg1[1]=w20;
  res1[0]=(&w16);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @20) */
  arg1[0]=(&w18);
  arg1[1]=w20;
  res1[0]=(&w17);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @20) */
  arg1[0]=(&w19);
  arg1[1]=w20;
  res1[0]=(&w18);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #22: @1 = horzcat(@21, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w1;
  *rr++ = w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #23: @21 = BSplineParametric(@0) */
  casadi_clear((&w21), 1);
  CASADI_PREFIX(nd_boor_eval)((&w21),1,casadi_c2,casadi_s4,casadi_s3,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #24: output[0][0] = @21 */
  if (res[0]) res[0][0] = w21;
  return 0;
}

/* adj1_r:(x,c[6],out_f[1x1,0nz],adj_f)->(adj_x,adj_c[6x1,0nz]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+2, *rr;
  const casadi_real **arg1=arg+4;
  casadi_real w0, *w1=w+8, *w2=w+25, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+61, w22, *w23=w+68;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x17) */
  casadi_clear(w1, 17);
  /* #2: @2 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w2);
  /* #3: {@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20} = horzsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[2];
  w6 = w2[3];
  w7 = w2[4];
  w8 = w2[5];
  w9 = w2[6];
  w10 = w2[7];
  w11 = w2[8];
  w12 = w2[9];
  w13 = w2[10];
  w14 = w2[11];
  w15 = w2[12];
  w16 = w2[13];
  w17 = w2[14];
  w18 = w2[15];
  w19 = w2[16];
  w20 = w2[17];
  /* #4: @21 = input[1][0] */
  casadi_copy(arg[1], 6, w21);
  /* #5: @22 = linear(@3, @21) */
  arg1[0]=(&w3);
  arg1[1]=w21;
  res1[0]=(&w22);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @21) */
  arg1[0]=(&w4);
  arg1[1]=w21;
  res1[0]=(&w3);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @21) */
  arg1[0]=(&w5);
  arg1[1]=w21;
  res1[0]=(&w4);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @21) */
  arg1[0]=(&w6);
  arg1[1]=w21;
  res1[0]=(&w5);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @21) */
  arg1[0]=(&w7);
  arg1[1]=w21;
  res1[0]=(&w6);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @21) */
  arg1[0]=(&w8);
  arg1[1]=w21;
  res1[0]=(&w7);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @21) */
  arg1[0]=(&w9);
  arg1[1]=w21;
  res1[0]=(&w8);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @21) */
  arg1[0]=(&w10);
  arg1[1]=w21;
  res1[0]=(&w9);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @21) */
  arg1[0]=(&w11);
  arg1[1]=w21;
  res1[0]=(&w10);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @21) */
  arg1[0]=(&w12);
  arg1[1]=w21;
  res1[0]=(&w11);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @21) */
  arg1[0]=(&w13);
  arg1[1]=w21;
  res1[0]=(&w12);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @21) */
  arg1[0]=(&w14);
  arg1[1]=w21;
  res1[0]=(&w13);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @21) */
  arg1[0]=(&w15);
  arg1[1]=w21;
  res1[0]=(&w14);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @21) */
  arg1[0]=(&w16);
  arg1[1]=w21;
  res1[0]=(&w15);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @21) */
  arg1[0]=(&w17);
  arg1[1]=w21;
  res1[0]=(&w16);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @21) */
  arg1[0]=(&w18);
  arg1[1]=w21;
  res1[0]=(&w17);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @21) */
  arg1[0]=(&w19);
  arg1[1]=w21;
  res1[0]=(&w18);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @21) */
  arg1[0]=(&w20);
  arg1[1]=w21;
  res1[0]=(&w19);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #23: @2 = horzcat(@22, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w2;
  *rr++ = w22;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  /* #24: @23 = sparse: 18-by-17, 34 nnz
   (0, 0) -> -30.6122
   (1, 0) -> 30.6122
   (1, 1) -> -29.4118
   (2, 1) -> 29.4118
   (2, 2) -> -15
   (3, 2) -> 15
   (3, 3) -> -15
   (4, 3) -> 15
   (4, 4) -> -15
   (5, 4) -> 15
   (5, 5) -> -15
   (6, 5) -> 15
   (6, 6) -> -15
   (7, 6) -> 15
   (7, 7) -> -15
   (8, 7) -> 15
   (8, 8) -> -15
   (9, 8) -> 15
   (9, 9) -> -15
   (10, 9) -> 15
   (10, 10) -> -15
   (11, 10) -> 15
   (11, 11) -> -15
   (12, 11) -> 15
   (12, 12) -> -15
   (13, 12) -> 15
   (13, 13) -> -15
   (14, 13) -> 15
   (14, 14) -> -15
   (15, 14) -> 15
   (15, 15) -> -29.4118
   (16, 15) -> 29.4118
   (16, 16) -> -30.6122
   (17, 16) -> 30.6122 */
  casadi_copy(casadi_c3, 34, w23);
  /* #25: @1 = mac(@2,@23,@1) */
  casadi_mtimes(w2, casadi_s7, w23, casadi_s6, w1, casadi_s5, w, 0);
  /* #26: @22 = BSplineParametric(@0) */
  casadi_clear((&w22), 1);
  CASADI_PREFIX(nd_boor_eval)((&w22),1,casadi_c4,casadi_s9,casadi_s8,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #27: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #28: @22 = (@22*@0) */
  w22 *= w0;
  /* #29: output[0][0] = @22 */
  if (res[0]) res[0][0] = w22;
  return 0;
}

/* adj1_y:(x,c[6],out_f[1x1,0nz],adj_f)->(adj_x,adj_c[6x1,0nz]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+2, *rr;
  const casadi_real **arg1=arg+4;
  casadi_real w0, *w1=w+8, *w2=w+25, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+61, w22, *w23=w+68;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x17) */
  casadi_clear(w1, 17);
  /* #2: @2 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w2);
  /* #3: {@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20} = horzsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[2];
  w6 = w2[3];
  w7 = w2[4];
  w8 = w2[5];
  w9 = w2[6];
  w10 = w2[7];
  w11 = w2[8];
  w12 = w2[9];
  w13 = w2[10];
  w14 = w2[11];
  w15 = w2[12];
  w16 = w2[13];
  w17 = w2[14];
  w18 = w2[15];
  w19 = w2[16];
  w20 = w2[17];
  /* #4: @21 = input[1][0] */
  casadi_copy(arg[1], 6, w21);
  /* #5: @22 = linear(@3, @21) */
  arg1[0]=(&w3);
  arg1[1]=w21;
  res1[0]=(&w22);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @21) */
  arg1[0]=(&w4);
  arg1[1]=w21;
  res1[0]=(&w3);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @21) */
  arg1[0]=(&w5);
  arg1[1]=w21;
  res1[0]=(&w4);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @21) */
  arg1[0]=(&w6);
  arg1[1]=w21;
  res1[0]=(&w5);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @21) */
  arg1[0]=(&w7);
  arg1[1]=w21;
  res1[0]=(&w6);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @21) */
  arg1[0]=(&w8);
  arg1[1]=w21;
  res1[0]=(&w7);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @21) */
  arg1[0]=(&w9);
  arg1[1]=w21;
  res1[0]=(&w8);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @21) */
  arg1[0]=(&w10);
  arg1[1]=w21;
  res1[0]=(&w9);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @21) */
  arg1[0]=(&w11);
  arg1[1]=w21;
  res1[0]=(&w10);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @21) */
  arg1[0]=(&w12);
  arg1[1]=w21;
  res1[0]=(&w11);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @21) */
  arg1[0]=(&w13);
  arg1[1]=w21;
  res1[0]=(&w12);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @21) */
  arg1[0]=(&w14);
  arg1[1]=w21;
  res1[0]=(&w13);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @21) */
  arg1[0]=(&w15);
  arg1[1]=w21;
  res1[0]=(&w14);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @21) */
  arg1[0]=(&w16);
  arg1[1]=w21;
  res1[0]=(&w15);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @21) */
  arg1[0]=(&w17);
  arg1[1]=w21;
  res1[0]=(&w16);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @21) */
  arg1[0]=(&w18);
  arg1[1]=w21;
  res1[0]=(&w17);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @21) */
  arg1[0]=(&w19);
  arg1[1]=w21;
  res1[0]=(&w18);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @21) */
  arg1[0]=(&w20);
  arg1[1]=w21;
  res1[0]=(&w19);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #23: @2 = horzcat(@22, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w2;
  *rr++ = w22;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  /* #24: @23 = sparse: 18-by-17, 34 nnz
   (0, 0) -> -30.6122
   (1, 0) -> 30.6122
   (1, 1) -> -29.4118
   (2, 1) -> 29.4118
   (2, 2) -> -15
   (3, 2) -> 15
   (3, 3) -> -15
   (4, 3) -> 15
   (4, 4) -> -15
   (5, 4) -> 15
   (5, 5) -> -15
   (6, 5) -> 15
   (6, 6) -> -15
   (7, 6) -> 15
   (7, 7) -> -15
   (8, 7) -> 15
   (8, 8) -> -15
   (9, 8) -> 15
   (9, 9) -> -15
   (10, 9) -> 15
   (10, 10) -> -15
   (11, 10) -> 15
   (11, 11) -> -15
   (12, 11) -> 15
   (12, 12) -> -15
   (13, 12) -> 15
   (13, 13) -> -15
   (14, 13) -> 15
   (14, 14) -> -15
   (15, 14) -> 15
   (15, 15) -> -29.4118
   (16, 15) -> 29.4118
   (16, 16) -> -30.6122
   (17, 16) -> 30.6122 */
  casadi_copy(casadi_c3, 34, w23);
  /* #25: @1 = mac(@2,@23,@1) */
  casadi_mtimes(w2, casadi_s7, w23, casadi_s6, w1, casadi_s5, w, 0);
  /* #26: @22 = BSplineParametric(@0) */
  casadi_clear((&w22), 1);
  CASADI_PREFIX(nd_boor_eval)((&w22),1,casadi_c4,casadi_s9,casadi_s8,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #27: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #28: @22 = (@22*@0) */
  w22 *= w0;
  /* #29: output[0][0] = @22 */
  if (res[0]) res[0][0] = w22;
  return 0;
}

/* adj1_x:(x,c[6],out_f[1x1,0nz],adj_f)->(adj_x,adj_c[6x1,0nz]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+2, *rr;
  const casadi_real **arg1=arg+4;
  casadi_real w0, *w1=w+8, *w2=w+25, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+61, w22, *w23=w+68;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x17) */
  casadi_clear(w1, 17);
  /* #2: @2 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w2);
  /* #3: {@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20} = horzsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[2];
  w6 = w2[3];
  w7 = w2[4];
  w8 = w2[5];
  w9 = w2[6];
  w10 = w2[7];
  w11 = w2[8];
  w12 = w2[9];
  w13 = w2[10];
  w14 = w2[11];
  w15 = w2[12];
  w16 = w2[13];
  w17 = w2[14];
  w18 = w2[15];
  w19 = w2[16];
  w20 = w2[17];
  /* #4: @21 = input[1][0] */
  casadi_copy(arg[1], 6, w21);
  /* #5: @22 = linear(@3, @21) */
  arg1[0]=(&w3);
  arg1[1]=w21;
  res1[0]=(&w22);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @21) */
  arg1[0]=(&w4);
  arg1[1]=w21;
  res1[0]=(&w3);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @21) */
  arg1[0]=(&w5);
  arg1[1]=w21;
  res1[0]=(&w4);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @21) */
  arg1[0]=(&w6);
  arg1[1]=w21;
  res1[0]=(&w5);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @21) */
  arg1[0]=(&w7);
  arg1[1]=w21;
  res1[0]=(&w6);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @21) */
  arg1[0]=(&w8);
  arg1[1]=w21;
  res1[0]=(&w7);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @21) */
  arg1[0]=(&w9);
  arg1[1]=w21;
  res1[0]=(&w8);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @21) */
  arg1[0]=(&w10);
  arg1[1]=w21;
  res1[0]=(&w9);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @21) */
  arg1[0]=(&w11);
  arg1[1]=w21;
  res1[0]=(&w10);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @21) */
  arg1[0]=(&w12);
  arg1[1]=w21;
  res1[0]=(&w11);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @21) */
  arg1[0]=(&w13);
  arg1[1]=w21;
  res1[0]=(&w12);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @21) */
  arg1[0]=(&w14);
  arg1[1]=w21;
  res1[0]=(&w13);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @21) */
  arg1[0]=(&w15);
  arg1[1]=w21;
  res1[0]=(&w14);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @21) */
  arg1[0]=(&w16);
  arg1[1]=w21;
  res1[0]=(&w15);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @21) */
  arg1[0]=(&w17);
  arg1[1]=w21;
  res1[0]=(&w16);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @21) */
  arg1[0]=(&w18);
  arg1[1]=w21;
  res1[0]=(&w17);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @21) */
  arg1[0]=(&w19);
  arg1[1]=w21;
  res1[0]=(&w18);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @21) */
  arg1[0]=(&w20);
  arg1[1]=w21;
  res1[0]=(&w19);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #23: @2 = horzcat(@22, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w2;
  *rr++ = w22;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  /* #24: @23 = sparse: 18-by-17, 34 nnz
   (0, 0) -> -30.6122
   (1, 0) -> 30.6122
   (1, 1) -> -29.4118
   (2, 1) -> 29.4118
   (2, 2) -> -15
   (3, 2) -> 15
   (3, 3) -> -15
   (4, 3) -> 15
   (4, 4) -> -15
   (5, 4) -> 15
   (5, 5) -> -15
   (6, 5) -> 15
   (6, 6) -> -15
   (7, 6) -> 15
   (7, 7) -> -15
   (8, 7) -> 15
   (8, 8) -> -15
   (9, 8) -> 15
   (9, 9) -> -15
   (10, 9) -> 15
   (10, 10) -> -15
   (11, 10) -> 15
   (11, 11) -> -15
   (12, 11) -> 15
   (12, 12) -> -15
   (13, 12) -> 15
   (13, 13) -> -15
   (14, 13) -> 15
   (14, 14) -> -15
   (15, 14) -> 15
   (15, 15) -> -29.4118
   (16, 15) -> 29.4118
   (16, 16) -> -30.6122
   (17, 16) -> 30.6122 */
  casadi_copy(casadi_c3, 34, w23);
  /* #25: @1 = mac(@2,@23,@1) */
  casadi_mtimes(w2, casadi_s7, w23, casadi_s6, w1, casadi_s5, w, 0);
  /* #26: @22 = BSplineParametric(@0) */
  casadi_clear((&w22), 1);
  CASADI_PREFIX(nd_boor_eval)((&w22),1,casadi_c4,casadi_s9,casadi_s8,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #27: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #28: @22 = (@22*@0) */
  w22 *= w0;
  /* #29: output[0][0] = @22 */
  if (res[0]) res[0][0] = w22;
  return 0;
}

/* fwd1_x:(x,c[6],out_f[1x1,0nz],fwd_x,fwd_c[6])->(fwd_f) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+5;
  casadi_real w0, *w1=w+8, *w2=w+25, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+61, w22, *w23=w+68;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x17) */
  casadi_clear(w1, 17);
  /* #2: @2 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w2);
  /* #3: {@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20} = horzsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[2];
  w6 = w2[3];
  w7 = w2[4];
  w8 = w2[5];
  w9 = w2[6];
  w10 = w2[7];
  w11 = w2[8];
  w12 = w2[9];
  w13 = w2[10];
  w14 = w2[11];
  w15 = w2[12];
  w16 = w2[13];
  w17 = w2[14];
  w18 = w2[15];
  w19 = w2[16];
  w20 = w2[17];
  /* #4: @21 = input[1][0] */
  casadi_copy(arg[1], 6, w21);
  /* #5: @22 = linear(@3, @21) */
  arg1[0]=(&w3);
  arg1[1]=w21;
  res1[0]=(&w22);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @21) */
  arg1[0]=(&w4);
  arg1[1]=w21;
  res1[0]=(&w3);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @21) */
  arg1[0]=(&w5);
  arg1[1]=w21;
  res1[0]=(&w4);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @21) */
  arg1[0]=(&w6);
  arg1[1]=w21;
  res1[0]=(&w5);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @21) */
  arg1[0]=(&w7);
  arg1[1]=w21;
  res1[0]=(&w6);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @21) */
  arg1[0]=(&w8);
  arg1[1]=w21;
  res1[0]=(&w7);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @21) */
  arg1[0]=(&w9);
  arg1[1]=w21;
  res1[0]=(&w8);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @21) */
  arg1[0]=(&w10);
  arg1[1]=w21;
  res1[0]=(&w9);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @21) */
  arg1[0]=(&w11);
  arg1[1]=w21;
  res1[0]=(&w10);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @21) */
  arg1[0]=(&w12);
  arg1[1]=w21;
  res1[0]=(&w11);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @21) */
  arg1[0]=(&w13);
  arg1[1]=w21;
  res1[0]=(&w12);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @21) */
  arg1[0]=(&w14);
  arg1[1]=w21;
  res1[0]=(&w13);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @21) */
  arg1[0]=(&w15);
  arg1[1]=w21;
  res1[0]=(&w14);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @21) */
  arg1[0]=(&w16);
  arg1[1]=w21;
  res1[0]=(&w15);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @21) */
  arg1[0]=(&w17);
  arg1[1]=w21;
  res1[0]=(&w16);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @21) */
  arg1[0]=(&w18);
  arg1[1]=w21;
  res1[0]=(&w17);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @21) */
  arg1[0]=(&w19);
  arg1[1]=w21;
  res1[0]=(&w18);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @21) */
  arg1[0]=(&w20);
  arg1[1]=w21;
  res1[0]=(&w19);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #23: @2 = horzcat(@22, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w2;
  *rr++ = w22;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  /* #24: @23 = sparse: 18-by-17, 34 nnz
   (0, 0) -> -30.6122
   (1, 0) -> 30.6122
   (1, 1) -> -29.4118
   (2, 1) -> 29.4118
   (2, 2) -> -15
   (3, 2) -> 15
   (3, 3) -> -15
   (4, 3) -> 15
   (4, 4) -> -15
   (5, 4) -> 15
   (5, 5) -> -15
   (6, 5) -> 15
   (6, 6) -> -15
   (7, 6) -> 15
   (7, 7) -> -15
   (8, 7) -> 15
   (8, 8) -> -15
   (9, 8) -> 15
   (9, 9) -> -15
   (10, 9) -> 15
   (10, 10) -> -15
   (11, 10) -> 15
   (11, 11) -> -15
   (12, 11) -> 15
   (12, 12) -> -15
   (13, 12) -> 15
   (13, 13) -> -15
   (14, 13) -> 15
   (14, 14) -> -15
   (15, 14) -> 15
   (15, 15) -> -29.4118
   (16, 15) -> 29.4118
   (16, 16) -> -30.6122
   (17, 16) -> 30.6122 */
  casadi_copy(casadi_c3, 34, w23);
  /* #25: @1 = mac(@2,@23,@1) */
  casadi_mtimes(w2, casadi_s7, w23, casadi_s6, w1, casadi_s5, w, 0);
  /* #26: @22 = BSplineParametric(@0) */
  casadi_clear((&w22), 1);
  CASADI_PREFIX(nd_boor_eval)((&w22),1,casadi_c4,casadi_s9,casadi_s8,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #27: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #28: @22 = (@22*@0) */
  w22 *= w0;
  /* #29: output[0][0] = @22 */
  if (res[0]) res[0][0] = w22;
  return 0;
}

/* fwd2_adj1_x:(x,c[6],out_f[1x1,0nz],adj_f,out_adj_x[1x1,0nz],out_adj_c[6x1,0nz],fwd_x[1x2],fwd_c[6x2],fwd_out_f[1x2,0nz],fwd_adj_f[1x2])->(fwd_adj_x[1x2],fwd_adj_c[6x2,0nz]) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+2, *rr;
  const casadi_real **arg1=arg+10;
  casadi_real w0, w1, *w2=w+9, *w3=w+25, *w4=w+42, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, *w23=w+78, w24, *w25=w+85, *w26=w+119;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = zeros(1x16) */
  casadi_clear(w2, 16);
  /* #3: @3 = zeros(1x17) */
  casadi_clear(w3, 17);
  /* #4: @4 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w4);
  /* #5: {@5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22} = horzsplit(@4) */
  w5 = w4[0];
  w6 = w4[1];
  w7 = w4[2];
  w8 = w4[3];
  w9 = w4[4];
  w10 = w4[5];
  w11 = w4[6];
  w12 = w4[7];
  w13 = w4[8];
  w14 = w4[9];
  w15 = w4[10];
  w16 = w4[11];
  w17 = w4[12];
  w18 = w4[13];
  w19 = w4[14];
  w20 = w4[15];
  w21 = w4[16];
  w22 = w4[17];
  /* #6: @23 = input[1][0] */
  casadi_copy(arg[1], 6, w23);
  /* #7: @24 = linear(@5, @23) */
  arg1[0]=(&w5);
  arg1[1]=w23;
  res1[0]=(&w24);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @23) */
  arg1[0]=(&w6);
  arg1[1]=w23;
  res1[0]=(&w5);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @23) */
  arg1[0]=(&w7);
  arg1[1]=w23;
  res1[0]=(&w6);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @23) */
  arg1[0]=(&w8);
  arg1[1]=w23;
  res1[0]=(&w7);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @23) */
  arg1[0]=(&w9);
  arg1[1]=w23;
  res1[0]=(&w8);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @23) */
  arg1[0]=(&w10);
  arg1[1]=w23;
  res1[0]=(&w9);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @23) */
  arg1[0]=(&w11);
  arg1[1]=w23;
  res1[0]=(&w10);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @23) */
  arg1[0]=(&w12);
  arg1[1]=w23;
  res1[0]=(&w11);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @23) */
  arg1[0]=(&w13);
  arg1[1]=w23;
  res1[0]=(&w12);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @23) */
  arg1[0]=(&w14);
  arg1[1]=w23;
  res1[0]=(&w13);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @23) */
  arg1[0]=(&w15);
  arg1[1]=w23;
  res1[0]=(&w14);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @23) */
  arg1[0]=(&w16);
  arg1[1]=w23;
  res1[0]=(&w15);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @23) */
  arg1[0]=(&w17);
  arg1[1]=w23;
  res1[0]=(&w16);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @23) */
  arg1[0]=(&w18);
  arg1[1]=w23;
  res1[0]=(&w17);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @23) */
  arg1[0]=(&w19);
  arg1[1]=w23;
  res1[0]=(&w18);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @23) */
  arg1[0]=(&w20);
  arg1[1]=w23;
  res1[0]=(&w19);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #23: @20 = linear(@21, @23) */
  arg1[0]=(&w21);
  arg1[1]=w23;
  res1[0]=(&w20);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #24: @21 = linear(@22, @23) */
  arg1[0]=(&w22);
  arg1[1]=w23;
  res1[0]=(&w21);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #25: @4 = horzcat(@24, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21) */
  rr=w4;
  *rr++ = w24;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  /* #26: @25 = sparse: 18-by-17, 34 nnz
   (0, 0) -> -30.6122
   (1, 0) -> 30.6122
   (1, 1) -> -29.4118
   (2, 1) -> 29.4118
   (2, 2) -> -15
   (3, 2) -> 15
   (3, 3) -> -15
   (4, 3) -> 15
   (4, 4) -> -15
   (5, 4) -> 15
   (5, 5) -> -15
   (6, 5) -> 15
   (6, 6) -> -15
   (7, 6) -> 15
   (7, 7) -> -15
   (8, 7) -> 15
   (8, 8) -> -15
   (9, 8) -> 15
   (9, 9) -> -15
   (10, 9) -> 15
   (10, 10) -> -15
   (11, 10) -> 15
   (11, 11) -> -15
   (12, 11) -> 15
   (12, 12) -> -15
   (13, 12) -> 15
   (13, 13) -> -15
   (14, 13) -> 15
   (14, 14) -> -15
   (15, 14) -> 15
   (15, 15) -> -29.4118
   (16, 15) -> 29.4118
   (16, 16) -> -30.6122
   (17, 16) -> 30.6122 */
  casadi_copy(casadi_c3, 34, w25);
  /* #27: @3 = mac(@4,@25,@3) */
  casadi_mtimes(w4, casadi_s7, w25, casadi_s6, w3, casadi_s5, w, 0);
  /* #28: @26 = sparse: 17-by-16, 32 nnz
   (0, 0) -> -20.4082
   (1, 0) -> 20.4082
   (1, 1) -> -19.6078
   (2, 1) -> 19.6078
   (2, 2) -> -19.6078
   (3, 2) -> 19.6078
   (3, 3) -> -10.2041
   (4, 3) -> 10.2041
   (4, 4) -> -19.6078
   (5, 4) -> 19.6078
   (5, 5) -> -19.6078
   (6, 5) -> 19.6078
   (6, 6) -> -10.2041
   (7, 6) -> 10.2041
   (7, 7) -> -19.6078
   (8, 7) -> 19.6078
   (8, 8) -> -19.6078
   (9, 8) -> 19.6078
   (9, 9) -> -10.2041
   (10, 9) -> 10.2041
   (10, 10) -> -19.6078
   (11, 10) -> 19.6078
   (11, 11) -> -19.6078
   (12, 11) -> 19.6078
   (12, 12) -> -10.2041
   (13, 12) -> 10.2041
   (13, 13) -> -19.6078
   (14, 13) -> 19.6078
   (14, 14) -> -19.6078
   (15, 14) -> 19.6078
   (15, 15) -> -20.4082
   (16, 15) -> 20.4082 */
  casadi_copy(casadi_c5, 32, w26);
  /* #29: @2 = mac(@3,@26,@2) */
  casadi_mtimes(w3, casadi_s5, w26, casadi_s11, w2, casadi_s10, w, 0);
  /* #30: @24 = BSplineParametric(@1) */
  casadi_clear((&w24), 1);
  CASADI_PREFIX(nd_boor_eval)((&w24),1,casadi_c6,casadi_s12,casadi_s2,casadi_s2,w2,1,(&w1),casadi_s0, iw, w);
  /* #31: @5 = input[6][0] */
  w5 = arg[6] ? arg[6][0] : 0;
  /* #32: @5 = (@24*@5) */
  w5  = (w24*w5);
  /* #33: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #34: @6 = BSplineParametric(@1) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c4,casadi_s9,casadi_s8,casadi_s2,w3,1,(&w1),casadi_s0, iw, w);
  /* #35: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #36: @1 = (@6*@1) */
  w1  = (w6*w1);
  /* #37: @5 = (@5+@1) */
  w5 += w1;
  /* #38: output[0][0] = @5 */
  if (res[0]) res[0][0] = w5;
  /* #39: @5 = input[6][1] */
  w5 = arg[6] ? arg[6][1] : 0;
  /* #40: @24 = (@24*@5) */
  w24 *= w5;
  /* #41: @0 = (@0*@24) */
  w0 *= w24;
  /* #42: @24 = input[9][1] */
  w24 = arg[9] ? arg[9][1] : 0;
  /* #43: @6 = (@6*@24) */
  w6 *= w24;
  /* #44: @0 = (@0+@6) */
  w0 += w6;
  /* #45: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  return 0;
}

/* fwd1_y:(x,c[6],out_f[1x1,0nz],fwd_x,fwd_c[6])->(fwd_f) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+5;
  casadi_real w0, *w1=w+8, *w2=w+25, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+61, w22, *w23=w+68;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x17) */
  casadi_clear(w1, 17);
  /* #2: @2 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w2);
  /* #3: {@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20} = horzsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[2];
  w6 = w2[3];
  w7 = w2[4];
  w8 = w2[5];
  w9 = w2[6];
  w10 = w2[7];
  w11 = w2[8];
  w12 = w2[9];
  w13 = w2[10];
  w14 = w2[11];
  w15 = w2[12];
  w16 = w2[13];
  w17 = w2[14];
  w18 = w2[15];
  w19 = w2[16];
  w20 = w2[17];
  /* #4: @21 = input[1][0] */
  casadi_copy(arg[1], 6, w21);
  /* #5: @22 = linear(@3, @21) */
  arg1[0]=(&w3);
  arg1[1]=w21;
  res1[0]=(&w22);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @21) */
  arg1[0]=(&w4);
  arg1[1]=w21;
  res1[0]=(&w3);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @21) */
  arg1[0]=(&w5);
  arg1[1]=w21;
  res1[0]=(&w4);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @21) */
  arg1[0]=(&w6);
  arg1[1]=w21;
  res1[0]=(&w5);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @21) */
  arg1[0]=(&w7);
  arg1[1]=w21;
  res1[0]=(&w6);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @21) */
  arg1[0]=(&w8);
  arg1[1]=w21;
  res1[0]=(&w7);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @21) */
  arg1[0]=(&w9);
  arg1[1]=w21;
  res1[0]=(&w8);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @21) */
  arg1[0]=(&w10);
  arg1[1]=w21;
  res1[0]=(&w9);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @21) */
  arg1[0]=(&w11);
  arg1[1]=w21;
  res1[0]=(&w10);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @21) */
  arg1[0]=(&w12);
  arg1[1]=w21;
  res1[0]=(&w11);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @21) */
  arg1[0]=(&w13);
  arg1[1]=w21;
  res1[0]=(&w12);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @21) */
  arg1[0]=(&w14);
  arg1[1]=w21;
  res1[0]=(&w13);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @21) */
  arg1[0]=(&w15);
  arg1[1]=w21;
  res1[0]=(&w14);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @21) */
  arg1[0]=(&w16);
  arg1[1]=w21;
  res1[0]=(&w15);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @21) */
  arg1[0]=(&w17);
  arg1[1]=w21;
  res1[0]=(&w16);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @21) */
  arg1[0]=(&w18);
  arg1[1]=w21;
  res1[0]=(&w17);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @21) */
  arg1[0]=(&w19);
  arg1[1]=w21;
  res1[0]=(&w18);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @21) */
  arg1[0]=(&w20);
  arg1[1]=w21;
  res1[0]=(&w19);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #23: @2 = horzcat(@22, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w2;
  *rr++ = w22;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  /* #24: @23 = sparse: 18-by-17, 34 nnz
   (0, 0) -> -30.6122
   (1, 0) -> 30.6122
   (1, 1) -> -29.4118
   (2, 1) -> 29.4118
   (2, 2) -> -15
   (3, 2) -> 15
   (3, 3) -> -15
   (4, 3) -> 15
   (4, 4) -> -15
   (5, 4) -> 15
   (5, 5) -> -15
   (6, 5) -> 15
   (6, 6) -> -15
   (7, 6) -> 15
   (7, 7) -> -15
   (8, 7) -> 15
   (8, 8) -> -15
   (9, 8) -> 15
   (9, 9) -> -15
   (10, 9) -> 15
   (10, 10) -> -15
   (11, 10) -> 15
   (11, 11) -> -15
   (12, 11) -> 15
   (12, 12) -> -15
   (13, 12) -> 15
   (13, 13) -> -15
   (14, 13) -> 15
   (14, 14) -> -15
   (15, 14) -> 15
   (15, 15) -> -29.4118
   (16, 15) -> 29.4118
   (16, 16) -> -30.6122
   (17, 16) -> 30.6122 */
  casadi_copy(casadi_c3, 34, w23);
  /* #25: @1 = mac(@2,@23,@1) */
  casadi_mtimes(w2, casadi_s7, w23, casadi_s6, w1, casadi_s5, w, 0);
  /* #26: @22 = BSplineParametric(@0) */
  casadi_clear((&w22), 1);
  CASADI_PREFIX(nd_boor_eval)((&w22),1,casadi_c4,casadi_s9,casadi_s8,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #27: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #28: @22 = (@22*@0) */
  w22 *= w0;
  /* #29: output[0][0] = @22 */
  if (res[0]) res[0][0] = w22;
  return 0;
}

/* fwd2_adj1_y:(x,c[6],out_f[1x1,0nz],adj_f,out_adj_x[1x1,0nz],out_adj_c[6x1,0nz],fwd_x[1x2],fwd_c[6x2],fwd_out_f[1x2,0nz],fwd_adj_f[1x2])->(fwd_adj_x[1x2],fwd_adj_c[6x2,0nz]) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+2, *rr;
  const casadi_real **arg1=arg+10;
  casadi_real w0, w1, *w2=w+9, *w3=w+25, *w4=w+42, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, *w23=w+78, w24, *w25=w+85, *w26=w+119;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = zeros(1x16) */
  casadi_clear(w2, 16);
  /* #3: @3 = zeros(1x17) */
  casadi_clear(w3, 17);
  /* #4: @4 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w4);
  /* #5: {@5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22} = horzsplit(@4) */
  w5 = w4[0];
  w6 = w4[1];
  w7 = w4[2];
  w8 = w4[3];
  w9 = w4[4];
  w10 = w4[5];
  w11 = w4[6];
  w12 = w4[7];
  w13 = w4[8];
  w14 = w4[9];
  w15 = w4[10];
  w16 = w4[11];
  w17 = w4[12];
  w18 = w4[13];
  w19 = w4[14];
  w20 = w4[15];
  w21 = w4[16];
  w22 = w4[17];
  /* #6: @23 = input[1][0] */
  casadi_copy(arg[1], 6, w23);
  /* #7: @24 = linear(@5, @23) */
  arg1[0]=(&w5);
  arg1[1]=w23;
  res1[0]=(&w24);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @23) */
  arg1[0]=(&w6);
  arg1[1]=w23;
  res1[0]=(&w5);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @23) */
  arg1[0]=(&w7);
  arg1[1]=w23;
  res1[0]=(&w6);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @23) */
  arg1[0]=(&w8);
  arg1[1]=w23;
  res1[0]=(&w7);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @23) */
  arg1[0]=(&w9);
  arg1[1]=w23;
  res1[0]=(&w8);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @23) */
  arg1[0]=(&w10);
  arg1[1]=w23;
  res1[0]=(&w9);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @23) */
  arg1[0]=(&w11);
  arg1[1]=w23;
  res1[0]=(&w10);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @23) */
  arg1[0]=(&w12);
  arg1[1]=w23;
  res1[0]=(&w11);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @23) */
  arg1[0]=(&w13);
  arg1[1]=w23;
  res1[0]=(&w12);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @23) */
  arg1[0]=(&w14);
  arg1[1]=w23;
  res1[0]=(&w13);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @23) */
  arg1[0]=(&w15);
  arg1[1]=w23;
  res1[0]=(&w14);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @23) */
  arg1[0]=(&w16);
  arg1[1]=w23;
  res1[0]=(&w15);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @23) */
  arg1[0]=(&w17);
  arg1[1]=w23;
  res1[0]=(&w16);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @23) */
  arg1[0]=(&w18);
  arg1[1]=w23;
  res1[0]=(&w17);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @23) */
  arg1[0]=(&w19);
  arg1[1]=w23;
  res1[0]=(&w18);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @23) */
  arg1[0]=(&w20);
  arg1[1]=w23;
  res1[0]=(&w19);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #23: @20 = linear(@21, @23) */
  arg1[0]=(&w21);
  arg1[1]=w23;
  res1[0]=(&w20);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #24: @21 = linear(@22, @23) */
  arg1[0]=(&w22);
  arg1[1]=w23;
  res1[0]=(&w21);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #25: @4 = horzcat(@24, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21) */
  rr=w4;
  *rr++ = w24;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  /* #26: @25 = sparse: 18-by-17, 34 nnz
   (0, 0) -> -30.6122
   (1, 0) -> 30.6122
   (1, 1) -> -29.4118
   (2, 1) -> 29.4118
   (2, 2) -> -15
   (3, 2) -> 15
   (3, 3) -> -15
   (4, 3) -> 15
   (4, 4) -> -15
   (5, 4) -> 15
   (5, 5) -> -15
   (6, 5) -> 15
   (6, 6) -> -15
   (7, 6) -> 15
   (7, 7) -> -15
   (8, 7) -> 15
   (8, 8) -> -15
   (9, 8) -> 15
   (9, 9) -> -15
   (10, 9) -> 15
   (10, 10) -> -15
   (11, 10) -> 15
   (11, 11) -> -15
   (12, 11) -> 15
   (12, 12) -> -15
   (13, 12) -> 15
   (13, 13) -> -15
   (14, 13) -> 15
   (14, 14) -> -15
   (15, 14) -> 15
   (15, 15) -> -29.4118
   (16, 15) -> 29.4118
   (16, 16) -> -30.6122
   (17, 16) -> 30.6122 */
  casadi_copy(casadi_c3, 34, w25);
  /* #27: @3 = mac(@4,@25,@3) */
  casadi_mtimes(w4, casadi_s7, w25, casadi_s6, w3, casadi_s5, w, 0);
  /* #28: @26 = sparse: 17-by-16, 32 nnz
   (0, 0) -> -20.4082
   (1, 0) -> 20.4082
   (1, 1) -> -19.6078
   (2, 1) -> 19.6078
   (2, 2) -> -19.6078
   (3, 2) -> 19.6078
   (3, 3) -> -10.2041
   (4, 3) -> 10.2041
   (4, 4) -> -19.6078
   (5, 4) -> 19.6078
   (5, 5) -> -19.6078
   (6, 5) -> 19.6078
   (6, 6) -> -10.2041
   (7, 6) -> 10.2041
   (7, 7) -> -19.6078
   (8, 7) -> 19.6078
   (8, 8) -> -19.6078
   (9, 8) -> 19.6078
   (9, 9) -> -10.2041
   (10, 9) -> 10.2041
   (10, 10) -> -19.6078
   (11, 10) -> 19.6078
   (11, 11) -> -19.6078
   (12, 11) -> 19.6078
   (12, 12) -> -10.2041
   (13, 12) -> 10.2041
   (13, 13) -> -19.6078
   (14, 13) -> 19.6078
   (14, 14) -> -19.6078
   (15, 14) -> 19.6078
   (15, 15) -> -20.4082
   (16, 15) -> 20.4082 */
  casadi_copy(casadi_c5, 32, w26);
  /* #29: @2 = mac(@3,@26,@2) */
  casadi_mtimes(w3, casadi_s5, w26, casadi_s11, w2, casadi_s10, w, 0);
  /* #30: @24 = BSplineParametric(@1) */
  casadi_clear((&w24), 1);
  CASADI_PREFIX(nd_boor_eval)((&w24),1,casadi_c6,casadi_s12,casadi_s2,casadi_s2,w2,1,(&w1),casadi_s0, iw, w);
  /* #31: @5 = input[6][0] */
  w5 = arg[6] ? arg[6][0] : 0;
  /* #32: @5 = (@24*@5) */
  w5  = (w24*w5);
  /* #33: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #34: @6 = BSplineParametric(@1) */
  casadi_clear((&w6), 1);
  CASADI_PREFIX(nd_boor_eval)((&w6),1,casadi_c4,casadi_s9,casadi_s8,casadi_s2,w3,1,(&w1),casadi_s0, iw, w);
  /* #35: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #36: @1 = (@6*@1) */
  w1  = (w6*w1);
  /* #37: @5 = (@5+@1) */
  w5 += w1;
  /* #38: output[0][0] = @5 */
  if (res[0]) res[0][0] = w5;
  /* #39: @5 = input[6][1] */
  w5 = arg[6] ? arg[6][1] : 0;
  /* #40: @24 = (@24*@5) */
  w24 *= w5;
  /* #41: @0 = (@0*@24) */
  w0 *= w24;
  /* #42: @24 = input[9][1] */
  w24 = arg[9] ? arg[9][1] : 0;
  /* #43: @6 = (@6*@24) */
  w6 *= w24;
  /* #44: @0 = (@0+@6) */
  w0 += w6;
  /* #45: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  return 0;
}

/* fwd1_r:(x,c[6],out_f[1x1,0nz],fwd_x,fwd_c[6])->(fwd_f) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+5;
  casadi_real w0, *w1=w+8, *w2=w+25, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+61, w22, *w23=w+68;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = zeros(1x17) */
  casadi_clear(w1, 17);
  /* #2: @2 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w2);
  /* #3: {@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20} = horzsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[2];
  w6 = w2[3];
  w7 = w2[4];
  w8 = w2[5];
  w9 = w2[6];
  w10 = w2[7];
  w11 = w2[8];
  w12 = w2[9];
  w13 = w2[10];
  w14 = w2[11];
  w15 = w2[12];
  w16 = w2[13];
  w17 = w2[14];
  w18 = w2[15];
  w19 = w2[16];
  w20 = w2[17];
  /* #4: @21 = input[1][0] */
  casadi_copy(arg[1], 6, w21);
  /* #5: @22 = linear(@3, @21) */
  arg1[0]=(&w3);
  arg1[1]=w21;
  res1[0]=(&w22);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #6: @3 = linear(@4, @21) */
  arg1[0]=(&w4);
  arg1[1]=w21;
  res1[0]=(&w3);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #7: @4 = linear(@5, @21) */
  arg1[0]=(&w5);
  arg1[1]=w21;
  res1[0]=(&w4);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @21) */
  arg1[0]=(&w6);
  arg1[1]=w21;
  res1[0]=(&w5);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @21) */
  arg1[0]=(&w7);
  arg1[1]=w21;
  res1[0]=(&w6);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @21) */
  arg1[0]=(&w8);
  arg1[1]=w21;
  res1[0]=(&w7);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @21) */
  arg1[0]=(&w9);
  arg1[1]=w21;
  res1[0]=(&w8);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @21) */
  arg1[0]=(&w10);
  arg1[1]=w21;
  res1[0]=(&w9);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @21) */
  arg1[0]=(&w11);
  arg1[1]=w21;
  res1[0]=(&w10);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @21) */
  arg1[0]=(&w12);
  arg1[1]=w21;
  res1[0]=(&w11);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @21) */
  arg1[0]=(&w13);
  arg1[1]=w21;
  res1[0]=(&w12);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @21) */
  arg1[0]=(&w14);
  arg1[1]=w21;
  res1[0]=(&w13);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @21) */
  arg1[0]=(&w15);
  arg1[1]=w21;
  res1[0]=(&w14);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @21) */
  arg1[0]=(&w16);
  arg1[1]=w21;
  res1[0]=(&w15);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @21) */
  arg1[0]=(&w17);
  arg1[1]=w21;
  res1[0]=(&w16);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @21) */
  arg1[0]=(&w18);
  arg1[1]=w21;
  res1[0]=(&w17);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @21) */
  arg1[0]=(&w19);
  arg1[1]=w21;
  res1[0]=(&w18);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @21) */
  arg1[0]=(&w20);
  arg1[1]=w21;
  res1[0]=(&w19);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #23: @2 = horzcat(@22, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w2;
  *rr++ = w22;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  /* #24: @23 = sparse: 18-by-17, 34 nnz
   (0, 0) -> -30.6122
   (1, 0) -> 30.6122
   (1, 1) -> -29.4118
   (2, 1) -> 29.4118
   (2, 2) -> -15
   (3, 2) -> 15
   (3, 3) -> -15
   (4, 3) -> 15
   (4, 4) -> -15
   (5, 4) -> 15
   (5, 5) -> -15
   (6, 5) -> 15
   (6, 6) -> -15
   (7, 6) -> 15
   (7, 7) -> -15
   (8, 7) -> 15
   (8, 8) -> -15
   (9, 8) -> 15
   (9, 9) -> -15
   (10, 9) -> 15
   (10, 10) -> -15
   (11, 10) -> 15
   (11, 11) -> -15
   (12, 11) -> 15
   (12, 12) -> -15
   (13, 12) -> 15
   (13, 13) -> -15
   (14, 13) -> 15
   (14, 14) -> -15
   (15, 14) -> 15
   (15, 15) -> -29.4118
   (16, 15) -> 29.4118
   (16, 16) -> -30.6122
   (17, 16) -> 30.6122 */
  casadi_copy(casadi_c3, 34, w23);
  /* #25: @1 = mac(@2,@23,@1) */
  casadi_mtimes(w2, casadi_s7, w23, casadi_s6, w1, casadi_s5, w, 0);
  /* #26: @22 = BSplineParametric(@0) */
  casadi_clear((&w22), 1);
  CASADI_PREFIX(nd_boor_eval)((&w22),1,casadi_c4,casadi_s9,casadi_s8,casadi_s2,w1,1,(&w0),casadi_s0, iw, w);
  /* #27: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #28: @22 = (@22*@0) */
  w22 *= w0;
  /* #29: output[0][0] = @22 */
  if (res[0]) res[0][0] = w22;
  return 0;
}

/* fwd1_adj1_r:(x,c[6],out_f[1x1,0nz],adj_f,out_adj_x[1x1,0nz],out_adj_c[6x1,0nz],fwd_x,fwd_c[6],fwd_out_f[1x1,0nz],fwd_adj_f)->(fwd_adj_x,fwd_adj_c[6x1,0nz]) */
static int casadi_f15(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+2, *rr;
  const casadi_real **arg1=arg+10;
  casadi_real w0, w1, *w2=w+9, *w3=w+25, *w4=w+42, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, *w23=w+78, w24, *w25=w+85, *w26=w+119;
  /* #0: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = zeros(1x16) */
  casadi_clear(w2, 16);
  /* #3: @3 = zeros(1x17) */
  casadi_clear(w3, 17);
  /* #4: @4 = [[0, 0.0326667, 0.0666667, 0.133333, 0.2, 0.266667, 0.333333, 0.4, 0.466667, 0.533333, 0.6, 0.666667, 0.733333, 0.8, 0.866667, 0.933333, 0.967333, 1]] */
  casadi_copy(casadi_c1, 18, w4);
  /* #5: {@5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22} = horzsplit(@4) */
  w5 = w4[0];
  w6 = w4[1];
  w7 = w4[2];
  w8 = w4[3];
  w9 = w4[4];
  w10 = w4[5];
  w11 = w4[6];
  w12 = w4[7];
  w13 = w4[8];
  w14 = w4[9];
  w15 = w4[10];
  w16 = w4[11];
  w17 = w4[12];
  w18 = w4[13];
  w19 = w4[14];
  w20 = w4[15];
  w21 = w4[16];
  w22 = w4[17];
  /* #6: @23 = input[1][0] */
  casadi_copy(arg[1], 6, w23);
  /* #7: @24 = linear(@5, @23) */
  arg1[0]=(&w5);
  arg1[1]=w23;
  res1[0]=(&w24);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = linear(@6, @23) */
  arg1[0]=(&w6);
  arg1[1]=w23;
  res1[0]=(&w5);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #9: @6 = linear(@7, @23) */
  arg1[0]=(&w7);
  arg1[1]=w23;
  res1[0]=(&w6);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #10: @7 = linear(@8, @23) */
  arg1[0]=(&w8);
  arg1[1]=w23;
  res1[0]=(&w7);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #11: @8 = linear(@9, @23) */
  arg1[0]=(&w9);
  arg1[1]=w23;
  res1[0]=(&w8);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = linear(@10, @23) */
  arg1[0]=(&w10);
  arg1[1]=w23;
  res1[0]=(&w9);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #13: @10 = linear(@11, @23) */
  arg1[0]=(&w11);
  arg1[1]=w23;
  res1[0]=(&w10);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #14: @11 = linear(@12, @23) */
  arg1[0]=(&w12);
  arg1[1]=w23;
  res1[0]=(&w11);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #15: @12 = linear(@13, @23) */
  arg1[0]=(&w13);
  arg1[1]=w23;
  res1[0]=(&w12);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #16: @13 = linear(@14, @23) */
  arg1[0]=(&w14);
  arg1[1]=w23;
  res1[0]=(&w13);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #17: @14 = linear(@15, @23) */
  arg1[0]=(&w15);
  arg1[1]=w23;
  res1[0]=(&w14);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = linear(@16, @23) */
  arg1[0]=(&w16);
  arg1[1]=w23;
  res1[0]=(&w15);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #19: @16 = linear(@17, @23) */
  arg1[0]=(&w17);
  arg1[1]=w23;
  res1[0]=(&w16);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #20: @17 = linear(@18, @23) */
  arg1[0]=(&w18);
  arg1[1]=w23;
  res1[0]=(&w17);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #21: @18 = linear(@19, @23) */
  arg1[0]=(&w19);
  arg1[1]=w23;
  res1[0]=(&w18);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #22: @19 = linear(@20, @23) */
  arg1[0]=(&w20);
  arg1[1]=w23;
  res1[0]=(&w19);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #23: @20 = linear(@21, @23) */
  arg1[0]=(&w21);
  arg1[1]=w23;
  res1[0]=(&w20);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #24: @21 = linear(@22, @23) */
  arg1[0]=(&w22);
  arg1[1]=w23;
  res1[0]=(&w21);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #25: @4 = horzcat(@24, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21) */
  rr=w4;
  *rr++ = w24;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  /* #26: @25 = sparse: 18-by-17, 34 nnz
   (0, 0) -> -30.6122
   (1, 0) -> 30.6122
   (1, 1) -> -29.4118
   (2, 1) -> 29.4118
   (2, 2) -> -15
   (3, 2) -> 15
   (3, 3) -> -15
   (4, 3) -> 15
   (4, 4) -> -15
   (5, 4) -> 15
   (5, 5) -> -15
   (6, 5) -> 15
   (6, 6) -> -15
   (7, 6) -> 15
   (7, 7) -> -15
   (8, 7) -> 15
   (8, 8) -> -15
   (9, 8) -> 15
   (9, 9) -> -15
   (10, 9) -> 15
   (10, 10) -> -15
   (11, 10) -> 15
   (11, 11) -> -15
   (12, 11) -> 15
   (12, 12) -> -15
   (13, 12) -> 15
   (13, 13) -> -15
   (14, 13) -> 15
   (14, 14) -> -15
   (15, 14) -> 15
   (15, 15) -> -29.4118
   (16, 15) -> 29.4118
   (16, 16) -> -30.6122
   (17, 16) -> 30.6122 */
  casadi_copy(casadi_c3, 34, w25);
  /* #27: @3 = mac(@4,@25,@3) */
  casadi_mtimes(w4, casadi_s7, w25, casadi_s6, w3, casadi_s5, w, 0);
  /* #28: @26 = sparse: 17-by-16, 32 nnz
   (0, 0) -> -20.4082
   (1, 0) -> 20.4082
   (1, 1) -> -19.6078
   (2, 1) -> 19.6078
   (2, 2) -> -19.6078
   (3, 2) -> 19.6078
   (3, 3) -> -10.2041
   (4, 3) -> 10.2041
   (4, 4) -> -19.6078
   (5, 4) -> 19.6078
   (5, 5) -> -19.6078
   (6, 5) -> 19.6078
   (6, 6) -> -10.2041
   (7, 6) -> 10.2041
   (7, 7) -> -19.6078
   (8, 7) -> 19.6078
   (8, 8) -> -19.6078
   (9, 8) -> 19.6078
   (9, 9) -> -10.2041
   (10, 9) -> 10.2041
   (10, 10) -> -19.6078
   (11, 10) -> 19.6078
   (11, 11) -> -19.6078
   (12, 11) -> 19.6078
   (12, 12) -> -10.2041
   (13, 12) -> 10.2041
   (13, 13) -> -19.6078
   (14, 13) -> 19.6078
   (14, 14) -> -19.6078
   (15, 14) -> 19.6078
   (15, 15) -> -20.4082
   (16, 15) -> 20.4082 */
  casadi_copy(casadi_c5, 32, w26);
  /* #29: @2 = mac(@3,@26,@2) */
  casadi_mtimes(w3, casadi_s5, w26, casadi_s11, w2, casadi_s10, w, 0);
  /* #30: @24 = BSplineParametric(@1) */
  casadi_clear((&w24), 1);
  CASADI_PREFIX(nd_boor_eval)((&w24),1,casadi_c6,casadi_s12,casadi_s2,casadi_s2,w2,1,(&w1),casadi_s0, iw, w);
  /* #31: @5 = input[6][0] */
  w5 = arg[6] ? arg[6][0] : 0;
  /* #32: @24 = (@24*@5) */
  w24 *= w5;
  /* #33: @0 = (@0*@24) */
  w0 *= w24;
  /* #34: @24 = BSplineParametric(@1) */
  casadi_clear((&w24), 1);
  CASADI_PREFIX(nd_boor_eval)((&w24),1,casadi_c4,casadi_s9,casadi_s8,casadi_s2,w3,1,(&w1),casadi_s0, iw, w);
  /* #35: @1 = input[9][0] */
  w1 = arg[9] ? arg[9][0] : 0;
  /* #36: @24 = (@24*@1) */
  w24 *= w1;
  /* #37: @0 = (@0+@24) */
  w0 += w24;
  /* #38: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* rockit_model_constr_h_fun_jac_uxt_hess:(i0[6],i1[4],i2,i3[],i4[12])->(o0,o1[10x1,3nz],o2[10x10,7nz],o3[1x0],o4[]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+5, *rr, *ss;
  const casadi_int *cii;
  const casadi_real **arg1=arg+5;
  casadi_real w0, w1, w2, *w3=w+154, w4, w5, *w6=w+162, *w7=w+168, w8, *w9=w+175, w11, w12, *w13=w+180, *w17=w+187, *w25=w+195, *w26=w+197, *w28=w+209, w29, w30, *w31=w+217, *w32=w+219, w33, *w34=w+222, *w35=w+225;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #2: @2 = input[4][3] */
  w2 = arg[4] ? arg[4][7] : 0;
  /* #3: @3 = @2[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s13, rr=w3, ss=(&w2); cii!=casadi_s13+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #4: @2 = x(@1, @3) */
  arg1[0]=(&w1);
  arg1[1]=w3;
  res1[0]=(&w2);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #5: @0 = (@0-@2) */
  w0 -= w2;
  /* #6: @2 = sq(@0) */
  w2 = casadi_sq( w0 );
  /* #7: @4 = input[0][1] */
  w4 = arg[0] ? arg[0][1] : 0;
  /* #8: @5 = input[4][4] */
  w5 = arg[4] ? arg[4][8] : 0;
  /* #9: @6 = @5[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s13, rr=w6, ss=(&w5); cii!=casadi_s13+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #10: @5 = y(@1, @6) */
  arg1[0]=(&w1);
  arg1[1]=w6;
  res1[0]=(&w5);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #11: @4 = (@4-@5) */
  w4 -= w5;
  /* #12: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #13: @2 = (@2+@5) */
  w2 += w5;
  /* #14: @5 = input[4][5] */
  w5 = arg[4] ? arg[4][9] : 0;
  /* #15: @7 = @5[0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s13, rr=w7, ss=(&w5); cii!=casadi_s13+6; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #16: @5 = r(@1, @7) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  res1[0]=(&w5);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #17: @8 = sq(@5) */
  w8 = casadi_sq( w5 );
  /* #18: @2 = (@2-@8) */
  w2 -= w8;
  /* #19: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #20: @9 = zeros(10x1,3nz) */
  casadi_clear(w9, 3);
  /* #21: @2 = (2.*@0) */
  w2 = (2.* w0 );
  /* #22: (@9[0] = @2) */
  for (rr=w9+0, ss=(&w2); rr!=w9+1; rr+=1) *rr = *ss++;
  /* #23: @8 = (2.*@4) */
  w8 = (2.* w4 );
  /* #24: (@9[1] = @8) */
  for (rr=w9+1, ss=(&w8); rr!=w9+2; rr+=1) *rr = *ss++;
  /* #25: @10 = 00 */
  /* #26: @11 = (2.*@5) */
  w11 = (2.* w5 );
  /* #27: @11 = (-@11) */
  w11 = (- w11 );
  /* #28: {@12, NULL} = adj1_r(@1, @7, @10, @11) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w11);
  res1[0]=(&w12);
  res1[1]=0;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #29: @10 = 00 */
  /* #30: @8 = (-@8) */
  w8 = (- w8 );
  /* #31: {@11, NULL} = adj1_y(@1, @6, @10, @8) */
  arg1[0]=(&w1);
  arg1[1]=w6;
  arg1[2]=0;
  arg1[3]=(&w8);
  res1[0]=(&w11);
  res1[1]=0;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #32: @12 = (@12+@11) */
  w12 += w11;
  /* #33: @10 = 00 */
  /* #34: @2 = (-@2) */
  w2 = (- w2 );
  /* #35: {@11, NULL} = adj1_x(@1, @3, @10, @2) */
  arg1[0]=(&w1);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w2);
  res1[0]=(&w11);
  res1[1]=0;
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #36: @12 = (@12+@11) */
  w12 += w11;
  /* #37: (@9[2] = @12) */
  for (rr=w9+2, ss=(&w12); rr!=w9+3; rr+=1) *rr = *ss++;
  /* #38: output[1][0] = @9 */
  casadi_copy(w9, 3, res[1]);
  /* #39: @13 = zeros(10x10,7nz) */
  casadi_clear(w13, 7);
  /* #40: @10 = 00 */
  /* #41: @14 = 00 */
  /* #42: @15 = 00 */
  /* #43: @16 = 00 */
  /* #44: @12 = input[2][0] */
  w12 = arg[2] ? arg[2][0] : 0;
  /* #45: @17 = ones(10x1,8nz) */
  casadi_fill(w17, 8, 1.);
  /* #46: {NULL, NULL, NULL, NULL, @11, NULL, NULL, NULL, NULL, NULL} = vertsplit(@17) */
  w11 = w17[4];
  /* #47: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #48: @11 = (@12*@11) */
  w11  = (w12*w11);
  /* #49: @18 = 00 */
  /* #50: @19 = 00 */
  /* #51: @20 = 00 */
  /* #52: @21 = 00 */
  /* #53: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #54: @0 = (@0*@12) */
  w0 *= w12;
  /* #55: @0 = (-@0) */
  w0 = (- w0 );
  /* #56: @22 = 00 */
  /* #57: {NULL, @23} = adj1_x(@1, @3, @21, @0) */
  arg1[0]=(&w1);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w0);
  res1[0]=0;
  res1[1]=0;
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #58: @24 = 00 */
  /* #59: @2 = ones(10x1,1nz) */
  w2 = 1.;
  /* #60: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @8, NULL} = vertsplit(@2) */
  w8 = w2;
  /* #61: @2 = horzcat(@24, @8) */
  rr=(&w2);
  *rr++ = w8;
  /* #62: @25 = dense(@2) */
  casadi_densify((&w2), casadi_s14, w25, 0);
  /* #63: @26 = zeros(6x2) */
  casadi_clear(w26, 12);
  /* #64: @24 = zeros(1x2,0nz) */
  /* #65: @2 = (-@11) */
  w2 = (- w11 );
  /* #66: @27 = 00 */
  /* #67: @28 = zeros(6x1) */
  casadi_clear(w28, 6);
  /* #68: @29 = fwd1_x(@1, @3, @27, @8, @28) */
  arg1[0]=(&w1);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w8);
  arg1[4]=w28;
  res1[0]=(&w29);
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #69: @29 = (-@29) */
  w29 = (- w29 );
  /* #70: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #71: @29 = (@12*@29) */
  w29  = (w12*w29);
  /* #72: @30 = (-@29) */
  w30 = (- w29 );
  /* #73: @31 = horzcat(@2, @30) */
  rr=w31;
  *rr++ = w2;
  *rr++ = w30;
  /* #74: {@32, NULL} = fwd2_adj1_x(@1, @3, @21, @0, @22, @23, @25, @26, @24, @31) */
  arg1[0]=(&w1);
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=(&w0);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=w25;
  arg1[7]=w26;
  arg1[8]=0;
  arg1[9]=w31;
  res1[0]=w32;
  res1[1]=0;
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #75: {@0, @2} = horzsplit(@32) */
  w0 = w32[0];
  w2 = w32[1];
  /* #76: @21 = 00 */
  /* #77: @32 = vertcat(@10, @14, @15, @16, @11, @18, @19, @20, @0, @21) */
  rr=w32;
  *rr++ = w11;
  *rr++ = w0;
  /* #78: @25 = @32[:2] */
  for (rr=w25, ss=w32+0; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #79: (@13[:8:4] = @25) */
  for (rr=w13+0, ss=w25; rr!=w13+8; rr+=4) *rr = *ss++;
  /* #80: @10 = 00 */
  /* #81: @14 = 00 */
  /* #82: @15 = 00 */
  /* #83: @16 = 00 */
  /* #84: @18 = 00 */
  /* #85: @11 = ones(10x1,1nz) */
  w11 = 1.;
  /* #86: {NULL, NULL, NULL, NULL, NULL, @0, NULL, NULL, NULL, NULL} = vertsplit(@11) */
  w0 = w11;
  /* #87: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #88: @0 = (@12*@0) */
  w0  = (w12*w0);
  /* #89: @19 = 00 */
  /* #90: @20 = 00 */
  /* #91: @21 = 00 */
  /* #92: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #93: @4 = (@4*@12) */
  w4 *= w12;
  /* #94: @4 = (-@4) */
  w4 = (- w4 );
  /* #95: @22 = 00 */
  /* #96: {NULL, @23} = adj1_y(@1, @6, @21, @4) */
  arg1[0]=(&w1);
  arg1[1]=w6;
  arg1[2]=0;
  arg1[3]=(&w4);
  res1[0]=0;
  res1[1]=0;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #97: @24 = 00 */
  /* #98: @11 = horzcat(@24, @8) */
  rr=(&w11);
  *rr++ = w8;
  /* #99: @25 = dense(@11) */
  casadi_densify((&w11), casadi_s14, w25, 0);
  /* #100: @26 = zeros(6x2) */
  casadi_clear(w26, 12);
  /* #101: @24 = zeros(1x2,0nz) */
  /* #102: @11 = (-@0) */
  w11 = (- w0 );
  /* #103: @27 = 00 */
  /* #104: @3 = zeros(6x1) */
  casadi_clear(w3, 6);
  /* #105: @30 = fwd1_y(@1, @6, @27, @8, @3) */
  arg1[0]=(&w1);
  arg1[1]=w6;
  arg1[2]=0;
  arg1[3]=(&w8);
  arg1[4]=w3;
  res1[0]=(&w30);
  if (casadi_f12(arg1, res1, iw, w, 0)) return 1;
  /* #106: @30 = (-@30) */
  w30 = (- w30 );
  /* #107: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #108: @30 = (@12*@30) */
  w30  = (w12*w30);
  /* #109: @33 = (-@30) */
  w33 = (- w30 );
  /* #110: @32 = horzcat(@11, @33) */
  rr=w32;
  *rr++ = w11;
  *rr++ = w33;
  /* #111: {@31, NULL} = fwd2_adj1_y(@1, @6, @21, @4, @22, @23, @25, @26, @24, @32) */
  arg1[0]=(&w1);
  arg1[1]=w6;
  arg1[2]=0;
  arg1[3]=(&w4);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=w25;
  arg1[7]=w26;
  arg1[8]=0;
  arg1[9]=w32;
  res1[0]=w31;
  res1[1]=0;
  if (casadi_f13(arg1, res1, iw, w, 0)) return 1;
  /* #112: {@4, @11} = horzsplit(@31) */
  w4 = w31[0];
  w11 = w31[1];
  /* #113: @21 = 00 */
  /* #114: @31 = vertcat(@10, @14, @15, @16, @18, @0, @19, @20, @4, @21) */
  rr=w31;
  *rr++ = w0;
  *rr++ = w4;
  /* #115: @25 = @31[:2] */
  for (rr=w25, ss=w31+0; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #116: (@13[2:8:3] = @25) */
  for (rr=w13+2, ss=w25; rr!=w13+8; rr+=3) *rr = *ss++;
  /* #117: @10 = 00 */
  /* #118: @14 = 00 */
  /* #119: @15 = 00 */
  /* #120: @16 = 00 */
  /* #121: @18 = 00 */
  /* #122: @19 = 00 */
  /* #123: @20 = 00 */
  /* #124: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #125: @5 = (@5*@12) */
  w5 *= w12;
  /* #126: @5 = (-@5) */
  w5 = (- w5 );
  /* #127: @21 = 00 */
  /* #128: {NULL, @22} = adj1_r(@1, @7, @20, @5) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w5);
  res1[0]=0;
  res1[1]=0;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #129: @6 = zeros(6x1) */
  casadi_clear(w6, 6);
  /* #130: @23 = 00 */
  /* #131: @24 = 00 */
  /* #132: @3 = zeros(6x1) */
  casadi_clear(w3, 6);
  /* #133: @0 = fwd1_r(@1, @7, @24, @8, @3) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w8);
  arg1[4]=w3;
  res1[0]=(&w0);
  if (casadi_f14(arg1, res1, iw, w, 0)) return 1;
  /* #134: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #135: @12 = (@12*@0) */
  w12 *= w0;
  /* #136: @12 = (-@12) */
  w12 = (- w12 );
  /* #137: {@0, NULL} = fwd1_adj1_r(@1, @7, @20, @5, @21, @22, @8, @6, @23, @12) */
  arg1[0]=(&w1);
  arg1[1]=w7;
  arg1[2]=0;
  arg1[3]=(&w5);
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=(&w8);
  arg1[7]=w6;
  arg1[8]=0;
  arg1[9]=(&w12);
  res1[0]=(&w0);
  res1[1]=0;
  if (casadi_f15(arg1, res1, iw, w, 0)) return 1;
  /* #138: @0 = (@0+@11) */
  w0 += w11;
  /* #139: @0 = (@0+@2) */
  w0 += w2;
  /* #140: @20 = 00 */
  /* #141: @9 = vertcat(@10, @14, @15, @16, @29, @30, @18, @19, @0, @20) */
  rr=w9;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w0;
  /* #142: @34 = @9[:3] */
  for (rr=w34, ss=w9+0; ss!=w9+3; ss+=1) *rr++ = *ss;
  /* #143: (@13[1, 3, 6] = @34) */
  for (cii=casadi_s15, rr=w13, ss=w34; cii!=casadi_s15+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #144: @35 = @13' */
  casadi_trans(w13,casadi_s16, w35, casadi_s16, iw);
  /* #145: output[2][0] = @35 */
  casadi_copy(w35, 7, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_constr_h_fun_jac_uxt_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rockit_model_constr_h_fun_jac_uxt_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_constr_h_fun_jac_uxt_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_constr_h_fun_jac_uxt_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rockit_model_constr_h_fun_jac_uxt_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_constr_h_fun_jac_uxt_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rockit_model_constr_h_fun_jac_uxt_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void rockit_model_constr_h_fun_jac_uxt_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_constr_h_fun_jac_uxt_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_constr_h_fun_jac_uxt_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real rockit_model_constr_h_fun_jac_uxt_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_constr_h_fun_jac_uxt_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_constr_h_fun_jac_uxt_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_constr_h_fun_jac_uxt_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s17;
    case 1: return casadi_s18;
    case 2: return casadi_s19;
    case 3: return casadi_s20;
    case 4: return casadi_s21;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_constr_h_fun_jac_uxt_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s19;
    case 1: return casadi_s22;
    case 2: return casadi_s16;
    case 3: return casadi_s23;
    case 4: return casadi_s20;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rockit_model_constr_h_fun_jac_uxt_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 33;
  if (sz_res) *sz_res = 25;
  if (sz_iw) *sz_iw = 11;
  if (sz_w) *sz_w = 232;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
